// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type PulseWidthOptionalType = Option<PulseWidthType>;

pub type ActuationStateOptionalType = Option<ActuationStateType>;

pub type ActuationComponentListType = Vec<ActuationComponentType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PulseWidthType {
    #[serde(rename = "LowInterval")]
    pub low_interval: crate::common::TimeSecondsType,
    #[serde(rename = "HighInterval")]
    pub high_interval: crate::common::TimeSecondsType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActuationCommandType {
    #[serde(rename = "OperationModeCommand")]
    pub operation_mode_command: crate::common::OperationModeOptionalType,
    #[serde(rename = "ScaledCommand")]
    pub scaled_command: crate::common::PercentOptionalType,
    #[serde(rename = "AngleCommand")]
    pub angle_command: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "SpeedCommand")]
    pub speed_command: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "VoltageCommand")]
    pub voltage_command: crate::common::VoltageVoltsOptionalType,
    #[serde(rename = "PulseWidth")]
    pub pulse_width: PulseWidthOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActuationStateType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusOptionalType,
    #[serde(rename = "Scaled")]
    pub scaled: crate::common::PercentOptionalType,
    #[serde(rename = "Angle")]
    pub angle: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "Speed")]
    pub speed: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "Current")]
    pub current: crate::common::CurrentAmperesOptionalType,
    #[serde(rename = "PulseWidth")]
    pub pulse_width: PulseWidthOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActuationStatusType {
    #[serde(rename = "CurrentState")]
    pub current_state: ActuationStateType,
    #[serde(rename = "ReferenceState")]
    pub reference_state: ActuationStateOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActuationComponentType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "ActuationCategory")]
    pub actuation_category: actuation_category_kind::Type,
    #[serde(rename = "MinimumLimit")]
    pub minimum_limit: ActuationStateOptionalType,
    #[serde(rename = "MaximumLimit")]
    pub maximum_limit: ActuationStateOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActuationCtrlSettingsType {
    #[serde(rename = "ActuationComponentList")]
    pub actuation_component_list: ActuationComponentListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

pub mod actuation_category_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Mode_Commanded")]
        Mode_Commanded,
        #[serde(rename = "Actuator")]
        Actuator,
        #[serde(rename = "Engine")]
        Engine,
        #[serde(rename = "Electric_Motor")]
        Electric_Motor,
        #[serde(rename = "Thrust_Engine")]
        Thrust_Engine,
        #[serde(rename = "Brake")]
        Brake,
        #[serde(rename = "Valve")]
        Valve,
        #[serde(rename = "Pump")]
        Pump,
        #[serde(rename = "Light")]
        Light,
    }

}

