// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type AlertIdType = String;

pub type AlertIdListType = Vec<AlertIdType>;

pub type AudioToneInfoOptionalType = Option<AudioToneInfoType>;

pub type AlarmConditionStatusListType = Vec<AlarmConditionStatusType>;

pub type ThreatConditionInfoListType = Vec<ThreatConditionInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AudioToneInfoType {
    #[serde(rename = "ToneFrequency")]
    pub tone_frequency: crate::common::FrequencyHertzType,
    #[serde(rename = "ToneModulationType")]
    pub tone_modulation_type: String,
    #[serde(rename = "ToneRepetitionFrequency")]
    pub tone_repetition_frequency: crate::common::FrequencyHertzType,
    #[serde(rename = "ToneMaxVolume")]
    pub tone_max_volume: crate::common::PowerWattsType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlarmConditionInfoType {
    #[serde(rename = "SubsystemName")]
    pub subsystem_name: String,
    #[serde(rename = "ComponentName")]
    pub component_name: String,
    #[serde(rename = "Measure")]
    pub measure: String,
    #[serde(rename = "Nature")]
    pub nature: String,
    #[serde(rename = "AlarmDescription")]
    pub alarm_description: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlarmConditionStatusType {
    #[serde(rename = "ConditionInfo")]
    pub condition_info: AlarmConditionInfoType,
    #[serde(rename = "Category")]
    pub category: alarm_category_kind::Type,
    #[serde(rename = "CategoryName")]
    pub category_name: String,
    #[serde(rename = "ConditionName")]
    pub condition_name: String,
    #[serde(rename = "HasMultipleInstances")]
    pub has_multiple_instances: bool,
    #[serde(rename = "IsOverridden")]
    pub is_overridden: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ThreatConditionInfoType {
    #[serde(rename = "TypeOfThreat")]
    pub type_of_threat: String,
    #[serde(rename = "ThreatStatus")]
    pub threat_status: String,
    #[serde(rename = "ThreatDescription")]
    pub threat_description: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlarmCategoryInfoType {
    #[serde(rename = "Abbreviation")]
    pub abbreviation: String,
    #[serde(rename = "IsAutoAcknowledged")]
    pub is_auto_acknowledged: bool,
    #[serde(rename = "AutoAcknowledgeTimeout")]
    pub auto_acknowledge_timeout: u32,
    #[serde(rename = "IsHiddenOnAcknowledge")]
    pub is_hidden_on_acknowledge: bool,
    #[serde(rename = "IsRepeated")]
    pub is_repeated: bool,
    #[serde(rename = "RepeatTimeout")]
    pub repeat_timeout: u32,
    #[serde(rename = "NotifyingTone")]
    pub notifying_tone: AudioToneInfoOptionalType,
    #[serde(rename = "RelevantCrewRoles")]
    pub relevant_crew_roles: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlertSettingsType {
    #[serde(rename = "AlarmCategoryWarning")]
    pub alarm_category_warning: AlarmCategoryInfoType,
    #[serde(rename = "AlarmCategoryAdvisory")]
    pub alarm_category_advisory: AlarmCategoryInfoType,
    #[serde(rename = "AlarmCategoryCaution")]
    pub alarm_category_caution: AlarmCategoryInfoType,
    #[serde(rename = "ThreatNotifyingTone")]
    pub threat_notifying_tone: AudioToneInfoOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlertStatusType {
    #[serde(rename = "AlarmConditionStatusList")]
    pub alarm_condition_status_list: AlarmConditionStatusListType,
    #[serde(rename = "ThreatConditionStatusList")]
    pub threat_condition_status_list: ThreatConditionInfoListType,
    #[serde(rename = "NumberOfActiveWarningAlarms")]
    pub number_of_active_warning_alarms: u32,
    #[serde(rename = "NumberOfActiveAdvisoryAlarms")]
    pub number_of_active_advisory_alarms: u32,
    #[serde(rename = "NumberOfActiveCautionAlarms")]
    pub number_of_active_caution_alarms: u32,
    #[serde(rename = "NumberOfActiveThreatAlerts")]
    pub number_of_active_threat_alerts: u32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlarmLogType {
    #[serde(rename = "Status")]
    pub status: alarm_status_kind::Type,
    #[serde(rename = "IsSuppressed")]
    pub is_suppressed: bool,
    #[serde(rename = "IsAcknowledged")]
    pub is_acknowledged: bool,
    #[serde(rename = "IsAutoAcknowledged")]
    pub is_auto_acknowledged: bool,
    #[serde(rename = "Condition")]
    pub condition: AlarmConditionInfoType,
    #[serde(rename = "Category")]
    pub category: alarm_category_kind::Type,
    #[serde(rename = "TimeRaised")]
    pub time_raised: crate::common::TimeType,
    #[serde(rename = "TimeAcknowledged")]
    pub time_acknowledged: crate::common::TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlarmAnnunciationType {
    #[serde(rename = "AlarmId")]
    pub alarm_id: AlertIdType,
    #[serde(rename = "ConditionInfo")]
    pub condition_info: AlarmConditionInfoType,
    #[serde(rename = "Category")]
    pub category: alarm_category_kind::Type,
    #[serde(rename = "NotifyingTone")]
    pub notifying_tone: AudioToneInfoOptionalType,
    #[serde(rename = "TimeRaised")]
    pub time_raised: crate::common::TimeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ThreatLogType {
    #[serde(rename = "ThreatInfo")]
    pub threat_info: ThreatConditionInfoType,
    #[serde(rename = "ObjectId")]
    pub object_id: crate::common::ObjectIdOptionalType,
    #[serde(rename = "LocationAtTimeOfDetection")]
    pub location_at_time_of_detection: crate::common::PositionOptionalType,
    #[serde(rename = "TimeOfDetection")]
    pub time_of_detection: crate::common::TimeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ThreatAnnunciationType {
    #[serde(rename = "ThreatAlertId")]
    pub threat_alert_id: AlertIdType,
    #[serde(rename = "ThreatInfo")]
    pub threat_info: ThreatConditionInfoType,
    #[serde(rename = "NotifyingTone")]
    pub notifying_tone: AudioToneInfoOptionalType,
    #[serde(rename = "TimeOfDetection")]
    pub time_of_detection: crate::common::TimeType,
}

pub mod alarm_category_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Critical_Warning")]
        Critical_Warning,
        #[serde(rename = "Warning")]
        Warning,
        #[serde(rename = "Caution")]
        Caution,
        #[serde(rename = "Advisory")]
        Advisory,
    }

}

pub mod alarm_status_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "Inactive")]
        Inactive,
        #[serde(rename = "Active")]
        Active,
    }

}

