// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlignmentSettingsType {
    #[serde(rename = "MinLateralStepsize")]
    pub min_lateral_stepsize: crate::common::SphericalPositionOptionalType,
    #[serde(rename = "MaxLateralStepsize")]
    pub max_lateral_stepsize: crate::common::SphericalPositionOptionalType,
    #[serde(rename = "MinLongitudinalStepsize")]
    pub min_longitudinal_stepsize: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "MaxLongitudinalStepsize")]
    pub max_longitudinal_stepsize: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "IsCmdAllowExternalAlignmentSupported")]
    pub is_cmd_allow_external_alignment_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AlignmentStatusType {
    #[serde(rename = "IsAlignmentActive")]
    pub is_alignment_active: bool,
    #[serde(rename = "IsAlignmentAllowed")]
    pub is_alignment_allowed: bool,
    #[serde(rename = "IsExternalAlignmentAllowed")]
    pub is_external_alignment_allowed: bool,
    #[serde(rename = "LateralOffset")]
    pub lateral_offset: crate::common::SphericalPositionOptionalType,
    #[serde(rename = "LongitudinalOffset")]
    pub longitudinal_offset: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "IsParallaxCorrectionEnabled")]
    pub is_parallax_correction_enabled: bool,
}

