// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type LogicLevelKindOptionalType = Option<logic_level_kind::Type>;

pub type AbsoluteSignalCorridorOptionalType = Option<AbsoluteSignalCorridorType>;

pub type ScaledSignalCorridorOptionalType = Option<ScaledSignalCorridorType>;

pub type SignalCorridorOptionalType = Option<SignalCorridorType>;

pub type AbsoluteSignalOptionalType = Option<AbsoluteSignalType>;

pub type ScaledSignalOptionalType = Option<ScaledSignalType>;

pub type SignalOptionalType = Option<SignalType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AbsoluteSignalCorridorType {
    #[serde(rename = "Offset")]
    pub offset: crate::common::VoltageVoltsType,
    #[serde(rename = "MinLevel")]
    pub min_level: crate::common::VoltageVoltsType,
    #[serde(rename = "MaxLevel")]
    pub max_level: crate::common::VoltageVoltsType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScaledSignalCorridorType {
    #[serde(rename = "Offset")]
    pub offset: crate::common::PercentType,
    #[serde(rename = "MinLevel")]
    pub min_level: crate::common::PercentType,
    #[serde(rename = "MaxLevel")]
    pub max_level: crate::common::PercentType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SignalCorridorType {
    #[serde(rename = "Absolute")]
    pub absolute: AbsoluteSignalCorridorOptionalType,
    #[serde(rename = "Scaled")]
    pub scaled: ScaledSignalCorridorOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AbsoluteSignalType {
    #[serde(rename = "Levels")]
    pub levels: crate::common::VoltageVoltsListType,
    #[serde(rename = "State")]
    pub state: LogicLevelKindOptionalType,
    #[serde(rename = "TimeStamp")]
    pub time_stamp: crate::common::TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScaledSignalType {
    #[serde(rename = "Levels")]
    pub levels: crate::common::PercentListType,
    #[serde(rename = "State")]
    pub state: LogicLevelKindOptionalType,
    #[serde(rename = "TimeStamp")]
    pub time_stamp: crate::common::TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SignalType {
    #[serde(rename = "Absolute")]
    pub absolute: AbsoluteSignalOptionalType,
    #[serde(rename = "Scaled")]
    pub scaled: ScaledSignalOptionalType,
}

pub mod logic_level_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "Low")]
        Low,
        #[serde(rename = "High")]
        High,
    }

}

