// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type FailureReasonOptionalType = Option<FailureReasonType>;

pub type UserIdentityOptionalType = Option<UserIdentityType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FailureReasonType {
    #[serde(rename = "Reason")]
    pub reason: login_failure_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LoginEventType {
    #[serde(rename = "Result")]
    pub result: auth_state_kind::Type,
    #[serde(rename = "FailureReason")]
    pub failure_reason: FailureReasonOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UserIdentityType {
    #[serde(rename = "Username")]
    pub username: String,
    #[serde(rename = "Roles")]
    pub roles: crate::common::ULongListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AuthStatusType {
    #[serde(rename = "State")]
    pub state: auth_state_kind::Type,
    #[serde(rename = "UserIdentity")]
    pub user_identity: UserIdentityOptionalType,
}

pub mod auth_state_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unauthenticated")]
        Unauthenticated,
        #[serde(rename = "Authenticated")]
        Authenticated,
    }

}

pub mod login_failure_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "InvalidPassword")]
        InvalidPassword,
        #[serde(rename = "UserNotFound")]
        UserNotFound,
        #[serde(rename = "ExpiredCredentials")]
        ExpiredCredentials,
        #[serde(rename = "Locked")]
        Locked,
        #[serde(rename = "LockedExternal")]
        LockedExternal,
    }

}

