// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type SupportedIBitRoutineListType = Vec<SupportedIBitRoutineType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SupportedIBitRoutineType {
    #[serde(rename = "RoutineName")]
    pub routine_name: String,
    #[serde(rename = "SupportedIBitNames")]
    pub supported_i_bit_names: crate::common::StringListType,
    #[serde(rename = "DurationMs")]
    pub duration_ms: crate::common::ULongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BitSettingsType {
    #[serde(rename = "IsIBitSupported")]
    pub is_i_bit_supported: bool,
    #[serde(rename = "IsCancelIBitRoutineSupported")]
    pub is_cancel_i_bit_routine_supported: bool,
    #[serde(rename = "IsPBitSupported")]
    pub is_p_bit_supported: bool,
    #[serde(rename = "IsCBitSupported")]
    pub is_c_bit_supported: bool,
    #[serde(rename = "SupportedIBitRoutines")]
    pub supported_i_bit_routines: SupportedIBitRoutineListType,
    #[serde(rename = "SupportedPBitNames")]
    pub supported_p_bit_names: crate::common::StringListType,
    #[serde(rename = "SupportedCBitNames")]
    pub supported_c_bit_names: crate::common::StringListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BitStatusType {
    #[serde(rename = "RoutineName")]
    pub routine_name: String,
    #[serde(rename = "Result")]
    pub result: test_result::Type,
    #[serde(rename = "ErrorCode")]
    pub error_code: crate::common::ULongOptionalType,
    #[serde(rename = "ErrorCodeDescription")]
    pub error_code_description: String,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

pub mod i_bit_routine_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Go")]
        Go,
        #[serde(rename = "No_Go")]
        No_Go,
        #[serde(rename = "Running")]
        Running,
        #[serde(rename = "Cancelled")]
        Cancelled,
        #[serde(rename = "Aborted")]
        Aborted,
    }

}

pub mod test_result {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "OK")]
        OK,
        #[serde(rename = "Warning")]
        Warning,
        #[serde(rename = "Reduced_Performance_Error")]
        Reduced_Performance_Error,
        #[serde(rename = "Fatal_Error")]
        Fatal_Error,
    }

}

