// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type BitRecordListType = Vec<BitRecordType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BitCtrlSettingsType {
    #[serde(rename = "SupportedActions")]
    pub supported_actions: crate::common::StringListType,
    #[serde(rename = "SupportedRecordNames")]
    pub supported_record_names: crate::common::StringListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BitCtrlStatusType {
    #[serde(rename = "CurrentAction")]
    pub current_action: String,
    #[serde(rename = "IsTestRunning")]
    pub is_test_running: bool,
    #[serde(rename = "IsStartTestAllowed")]
    pub is_start_test_allowed: bool,
    #[serde(rename = "TotalNoRecords")]
    pub total_no_records: u32,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BitRecordType {
    #[serde(rename = "RecordName")]
    pub record_name: String,
    #[serde(rename = "Status")]
    pub status: crate::built_in_test::BitStatusType,
    #[serde(rename = "Timestamp")]
    pub timestamp: crate::common::TimeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct HistoricalBitRecordParamsType {
    #[serde(rename = "RecordListId")]
    pub record_list_id: String,
    #[serde(rename = "IndexOfFirstRecord")]
    pub index_of_first_record: u32,
    #[serde(rename = "FilterExpression")]
    pub filter_expression: String,
}

