// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type PolarityHotColorOptionalType = Option<polarity_hot_color::Type>;

pub type ZoomStateListType = Vec<ZoomStateType>;

pub type RenderSettingsOptionalType = Option<RenderSettingsType>;

pub type SafetyCodeListType = Vec<SafetyCodeType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SupportedPolarityHotColorType {
    #[serde(rename = "IsWhiteSupported")]
    pub is_white_supported: bool,
    #[serde(rename = "IsBlackSupported")]
    pub is_black_supported: bool,
    #[serde(rename = "IsRedSupported")]
    pub is_red_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ZoomStateType {
    #[serde(rename = "Level")]
    pub level: crate::common::PercentType,
    #[serde(rename = "Fov")]
    pub fov: crate::common::DegreeRegionType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RenderSettingsType {
    #[serde(rename = "renderWidth")]
    pub render_width: i32,
    #[serde(rename = "renderHeight")]
    pub render_height: i32,
    #[serde(rename = "renderPosX")]
    pub render_pos_x: i32,
    #[serde(rename = "renderPosY")]
    pub render_pos_y: i32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CameraSettingsType {
    #[serde(rename = "ZoomStateList")]
    pub zoom_state_list: ZoomStateListType,
    #[serde(rename = "FocusStepSize")]
    pub focus_step_size: crate::common::PercentType,
    #[serde(rename = "BrightnessStepSize")]
    pub brightness_step_size: crate::common::PercentType,
    #[serde(rename = "ContrastStepSize")]
    pub contrast_step_size: crate::common::PercentType,
    #[serde(rename = "GainStepSize")]
    pub gain_step_size: crate::common::PercentType,
    #[serde(rename = "AlphaBlendingStepSize")]
    pub alpha_blending_step_size: crate::common::PercentType,
    #[serde(rename = "AvailableApertures")]
    pub available_apertures: crate::common::ProportionalListType,
    #[serde(rename = "IsAutoFocusSupported")]
    pub is_auto_focus_supported: bool,
    #[serde(rename = "IsFocusSupported")]
    pub is_focus_supported: bool,
    #[serde(rename = "IsFocusEngineSupported")]
    pub is_focus_engine_supported: bool,
    #[serde(rename = "IsDigitalZoomSupported")]
    pub is_digital_zoom_supported: bool,
    #[serde(rename = "IsZoomSupported")]
    pub is_zoom_supported: bool,
    #[serde(rename = "IsZoomEngineSupported")]
    pub is_zoom_engine_supported: bool,
    #[serde(rename = "IsAutoBrightnessSupported")]
    pub is_auto_brightness_supported: bool,
    #[serde(rename = "IsBrightnessSupported")]
    pub is_brightness_supported: bool,
    #[serde(rename = "IsAutoContrastSupported")]
    pub is_auto_contrast_supported: bool,
    #[serde(rename = "IsContrastSupported")]
    pub is_contrast_supported: bool,
    #[serde(rename = "IsPolaritySupported")]
    pub is_polarity_supported: bool,
    #[serde(rename = "SupportedHotColors")]
    pub supported_hot_colors: SupportedPolarityHotColorType,
    #[serde(rename = "IsEconomyModeSupported")]
    pub is_economy_mode_supported: bool,
    #[serde(rename = "IsCoolerSupported")]
    pub is_cooler_supported: bool,
    #[serde(rename = "IsAutoGainSupported")]
    pub is_auto_gain_supported: bool,
    #[serde(rename = "IsGainSupported")]
    pub is_gain_supported: bool,
    #[serde(rename = "IsExposureSupported")]
    pub is_exposure_supported: bool,
    #[serde(rename = "IsAutoExposureSupported")]
    pub is_auto_exposure_supported: bool,
    #[serde(rename = "IsSetApertureSupported")]
    pub is_set_aperture_supported: bool,
    #[serde(rename = "IsExternalTriggerModeSupported")]
    pub is_external_trigger_mode_supported: bool,
    #[serde(rename = "IsGrabbingSupported")]
    pub is_grabbing_supported: bool,
    #[serde(rename = "IsRegionOfInterestSupported")]
    pub is_region_of_interest_supported: bool,
    #[serde(rename = "IsCalibrateNucSupported")]
    pub is_calibrate_nuc_supported: bool,
    #[serde(rename = "IsAbortCalibrateNucSupported")]
    pub is_abort_calibrate_nuc_supported: bool,
    #[serde(rename = "IsFalseColorSupported")]
    pub is_false_color_supported: bool,
    #[serde(rename = "SupportedFalseColorAlgorithms")]
    pub supported_false_color_algorithms: crate::common::StringListType,
    #[serde(rename = "IsOperationModeSupported")]
    pub is_operation_mode_supported: bool,
    #[serde(rename = "IsAlphaBlendingSupported")]
    pub is_alpha_blending_supported: bool,
    #[serde(rename = "IsInfraredDynamicModeSupported")]
    pub is_infrared_dynamic_mode_supported: bool,
    #[serde(rename = "IsFreezeImageSupported")]
    pub is_freeze_image_supported: bool,
    #[serde(rename = "IsHdrSupported")]
    pub is_hdr_supported: bool,
    #[serde(rename = "SupportedCameraPresets")]
    pub supported_camera_presets: crate::common::StringListType,
    #[serde(rename = "RenderSettings")]
    pub render_settings: RenderSettingsOptionalType,
    #[serde(rename = "Position")]
    pub position: crate::common::PositionOptionalType,
    #[serde(rename = "Rotation")]
    pub rotation: crate::common::EulerAttitudeOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CameraStatusType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
    #[serde(rename = "IsAutoFocusEnabled")]
    pub is_auto_focus_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsAutoFocusChangeInProgress")]
    pub is_auto_focus_change_in_progress: bool,
    #[serde(rename = "FocusLevel")]
    pub focus_level: crate::common::PercentOptionalType,
    #[serde(rename = "IsFocusLevelChangeInProgress")]
    pub is_focus_level_change_in_progress: bool,
    #[serde(rename = "IsFocusEngineRunning")]
    pub is_focus_engine_running: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsFocusEngineChangeInProgress")]
    pub is_focus_engine_change_in_progress: bool,
    #[serde(rename = "ZoomState")]
    pub zoom_state: ZoomStateType,
    #[serde(rename = "IsDigitalZoomEnabled")]
    pub is_digital_zoom_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsDigitalZoomChangeInProgress")]
    pub is_digital_zoom_change_in_progress: bool,
    #[serde(rename = "IsZoomLevelChangeInProgress")]
    pub is_zoom_level_change_in_progress: bool,
    #[serde(rename = "PredefinedZoomFov")]
    pub predefined_zoom_fov: crate::common::UShortOptionalType,
    #[serde(rename = "IsPredefinedZoomFovChangeInProgress")]
    pub is_predefined_zoom_fov_change_in_progress: bool,
    #[serde(rename = "IsZoomFovRegionChangeInProgress")]
    pub is_zoom_fov_region_change_in_progress: bool,
    #[serde(rename = "IsZoomEngineRunning")]
    pub is_zoom_engine_running: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsZoomEngineChangeInProgress")]
    pub is_zoom_engine_change_in_progress: bool,
    #[serde(rename = "IsAutoBrightnessEnabled")]
    pub is_auto_brightness_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "BrightnessLevel")]
    pub brightness_level: crate::common::PercentOptionalType,
    #[serde(rename = "IsAutoContrastEnabled")]
    pub is_auto_contrast_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "ContrastLevel")]
    pub contrast_level: crate::common::PercentOptionalType,
    #[serde(rename = "PolarityHotIs")]
    pub polarity_hot_is: PolarityHotColorOptionalType,
    #[serde(rename = "IsEconomyModeEnabled")]
    pub is_economy_mode_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsCoolerEnabled")]
    pub is_cooler_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "Temperature")]
    pub temperature: crate::common::TemperatureKelvinsOptionalType,
    #[serde(rename = "IsCommunicationActive")]
    pub is_communication_active: bool,
    #[serde(rename = "IsAutoGainEnabled")]
    pub is_auto_gain_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "GainLevel")]
    pub gain_level: crate::common::PercentOptionalType,
    #[serde(rename = "IsAutoExposureEnabled")]
    pub is_auto_exposure_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "ShutterSpeedPerSec")]
    pub shutter_speed_per_sec: crate::common::UShortOptionalType,
    #[serde(rename = "Aperture")]
    pub aperture: crate::common::ProportionalOptionalType,
    #[serde(rename = "IsExternalTriggerModeEnabled")]
    pub is_external_trigger_mode_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsGrabbingRunning")]
    pub is_grabbing_running: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "RegionOfInterest")]
    pub region_of_interest: crate::common::PixelRegionOptionalType,
    #[serde(rename = "CoolerOperatingHoursCountTotal")]
    pub cooler_operating_hours_count_total: crate::common::ULongLongOptionalType,
    #[serde(rename = "ElectronicOperatingHoursCountTotal")]
    pub electronic_operating_hours_count_total: crate::common::ULongLongOptionalType,
    #[serde(rename = "SensorResolution")]
    pub sensor_resolution: crate::common::PixelRectSizeOptionalType,
    #[serde(rename = "IsFalseColorEnabled")]
    pub is_false_color_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "IsInfraredDynamicModeEnabled")]
    pub is_infrared_dynamic_mode_enabled: crate::common::GeneralStatusOptionalType,
    #[serde(rename = "HdrMode")]
    pub hdr_mode: i32,
    #[serde(rename = "FalseColorAlgorithmName")]
    pub false_color_algorithm_name: String,
    #[serde(rename = "Preset")]
    pub preset: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SafetyCodeType {
    #[serde(rename = "StartBuffer")]
    pub start_buffer: crate::common::UShortOptionalType,
    #[serde(rename = "SourceId")]
    pub source_id: crate::common::ByteOptionalType,
    #[serde(rename = "TimeStamp")]
    pub time_stamp: crate::common::UShortOptionalType,
    #[serde(rename = "Checksum")]
    pub checksum: crate::common::UShortOptionalType,
    #[serde(rename = "DisplayMask")]
    pub display_mask: crate::common::ByteOptionalType,
    #[serde(rename = "RegionOfInterest")]
    pub region_of_interest: crate::common::PixelRegionOptionalType,
}

pub mod scale_direction {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Increase")]
        Increase,
        #[serde(rename = "Decrease")]
        Decrease,
    }

}

pub mod polarity_hot_color {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "White")]
        White,
        #[serde(rename = "Black")]
        Black,
        #[serde(rename = "Red")]
        Red,
    }

}

pub mod auto_focus_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Stop")]
        Stop,
        #[serde(rename = "Start")]
        Start,
        #[serde(rename = "Hold")]
        Hold,
        #[serde(rename = "Infinity")]
        Infinity,
    }

}

