// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ObjectIdType = String;

pub type ObjectIdOptionalType = Option<ObjectIdType>;

pub type ObjectIdListType = Vec<ObjectIdType>;

pub type DoubleOptionalType = Option<f64>;

pub type DoubleListType = Vec<f64>;

pub type DoubleMatrixType = Vec<DoubleListType>;

pub type LongOptionalType = Option<i32>;

pub type ULongOptionalType = Option<u32>;

pub type ULongListType = Vec<u32>;

pub type ULongLongListType = Vec<u64>;

pub type LongLongOptionalType = Option<i64>;

pub type ULongLongOptionalType = Option<u64>;

pub type UShortOptionalType = Option<u16>;

pub type BooleanOptionalType = Option<bool>;

pub type ByteSeqType = Vec<u8>;

pub type ByteOptionalType = Option<u8>;

pub type StringOptionalType = Option<String>;

pub type StringListType = Vec<String>;

pub type BoundedStringType = String;

pub type BoundedStringOptionalType = Option<BoundedStringType>;

pub type ProportionalType = f64;

pub type ProportionalOptionalType = Option<ProportionalType>;

pub type ProportionalListType = Vec<ProportionalType>;

pub type PercentType = f64;

pub type PercentOptionalType = Option<PercentType>;

pub type PercentListType = Vec<PercentType>;

pub type TimeSecondsType = f64;

pub type TimeSecondsOptionalType = Option<TimeSecondsType>;

pub type TimeSecondsListType = Vec<TimeSecondsType>;

pub type MassKilogramsType = f64;

pub type MassKilogramsOptionalType = Option<MassKilogramsType>;

pub type MomentOfInertiaKilogramMetresSquaredType = f64;

pub type TemperatureKelvinsType = f64;

pub type TemperatureKelvinsOptionalType = Option<TemperatureKelvinsType>;

pub type TemperatureKelvinsListType = Vec<TemperatureKelvinsType>;

pub type PressurePascalsType = f64;

pub type PressurePascalsOptionalType = Option<PressurePascalsType>;

pub type PowerWattsType = f64;

pub type PowerWattsOptionalType = Option<PowerWattsType>;

pub type FrequencyHertzType = f64;

pub type FrequencyHertzOptionalType = Option<FrequencyHertzType>;

pub type AmplitudeDecibelsType = f64;

pub type AmplitudeDecibelsOptionalType = Option<AmplitudeDecibelsType>;

pub type AmplitudeScaledType = f64;

pub type AmplitudeScaledOptionalType = Option<AmplitudeScaledType>;

pub type PowerLevelDecibelWattsType = f64;

pub type PowerLevelDecibelWattsOptionalType = Option<PowerLevelDecibelWattsType>;

pub type MagneticFluxDensityTeslasType = f64;

pub type MagneticFluxDensityTeslasOptionalType = Option<MagneticFluxDensityTeslasType>;

pub type VoltageVoltsType = f64;

pub type VoltageVoltsOptionalType = Option<VoltageVoltsType>;

pub type VoltageVoltsListType = Vec<VoltageVoltsType>;

pub type CurrentAmperesType = f64;

pub type CurrentAmperesOptionalType = Option<CurrentAmperesType>;

pub type CurrentAmperesListType = Vec<CurrentAmperesType>;

pub type RateOfFireRpmType = f64;

pub type RateOfFireRpmOptionalType = Option<RateOfFireRpmType>;

pub type DistanceMetersType = f64;

pub type DistanceMetersOptionalType = Option<DistanceMetersType>;

pub type AngleRadiansType = f64;

pub type AngleRadiansOptionalType = Option<AngleRadiansType>;

pub type AngleDegreesType = f64;

pub type AngleDegreesOptionalType = Option<AngleDegreesType>;

pub type AngleDegreesListType = Vec<AngleDegreesType>;

pub type AngleRateDegreesPerSecType = f64;

pub type AngleRateDegreesPerSecOptionalType = Option<AngleRateDegreesPerSecType>;

pub type AngularAccelerationDegreesPerSecPerSecType = f64;

pub type AngularAccelerationDegreesPerSecPerSecOptionalType = Option<AngularAccelerationDegreesPerSecPerSecType>;

pub type SpeedMetersPerSecType = f64;

pub type SpeedMetersPerSecOptionalType = Option<SpeedMetersPerSecType>;

pub type AccelerationMetersPerSecPerSecType = f64;

pub type AccelerationMetersPerSecPerSecOptionalType = Option<AccelerationMetersPerSecPerSecType>;

pub type BitrateKiloBitsPerSecType = u32;

pub type BitrateKiloBitsPerSecOptionalType = Option<BitrateKiloBitsPerSecType>;

pub type DetectionType = u32;

pub type SensorType = u32;

pub type SensorOptionalType = Option<SensorType>;

pub type IdentityType = u32;

pub type IdentityOptionalType = Option<IdentityType>;

pub type ThreatLevelType = i32;

pub type ThreatLevelOptionalType = Option<ThreatLevelType>;

pub type ObjectClassificationOptionalType = Option<ObjectClassificationType>;

pub type ObjectClassificationListType = Vec<ObjectClassificationType>;

pub type GeneralStatusOptionalType = Option<general_status::Type>;

pub type PropertyOptionalType = Option<PropertyType>;

pub type PropertyListType = Vec<PropertyType>;

pub type OperationModeStateOptionalType = Option<operation_mode_state_kind::Type>;

pub type ModeTransitionOptionalType = Option<mode_transition_kind::Type>;

pub type OperationModeOptionalType = Option<OperationModeType>;

pub type OperationModeListType = Vec<OperationModeType>;

pub type OperationFaultStateOptionalType = Option<operation_fault_state_kind::Type>;

pub type OperationFaultListType = Vec<OperationFaultType>;

pub type ModeTransitionInfoOptionalType = Option<ModeTransitionInfoType>;

pub type OperationStatusOptionalType = Option<OperationStatusType>;

pub type OperationStatusListType = Vec<OperationStatusType>;

pub type OpticalSensorModeListType = Vec<optical_sensor_mode::Type>;

pub type ZoomFactorListType = Vec<zoom_factor::Type>;

pub type TimeOptionalType = Option<TimeType>;

pub type UnixTimeType = TimeType;

pub type UnixTimeOptionalType = Option<UnixTimeType>;

pub type UtcOptionalType = Option<UtcType>;

pub type DurationOptionalType = Option<DurationType>;

pub type TimeIntervalOptionalType = Option<TimeIntervalType>;

pub type TimeIntervalListType = Vec<TimeIntervalType>;

pub type AxisDirectionOptionalType = Option<AxisDirectionType>;

pub type AxisScalarOptionalType = Option<AxisScalarType>;

pub type MagneticFluxDensityOptionalType = Option<MagneticFluxDensityType>;

pub type UncertaintyOptionalType = Option<UncertaintyType>;

pub type CartesianPositionOptionalType = Option<CartesianPositionType>;

pub type CartesianPositionListType = Vec<CartesianPositionType>;

pub type SphericalPositionOptionalType = Option<SphericalPositionType>;

pub type SphericalPositionListType = Vec<SphericalPositionType>;

pub type EllipsoidalPositionOptionalType = Option<EllipsoidalPositionType>;

pub type EllipsoidalPositionListType = Vec<EllipsoidalPositionType>;

pub type PositionOptionalType = Option<PositionType>;

pub type PositionListType = Vec<PositionType>;

pub type EulerAttitudeOptionalType = Option<EulerAttitudeType>;

pub type AttitudeOptionalType = Option<AttitudeType>;

pub type AttitudeListType = Vec<AttitudeType>;

pub type CartesianLinearVelocityOptionalType = Option<CartesianLinearVelocityType>;

pub type SphericalLinearVelocityOptionalType = Option<SphericalLinearVelocityType>;

pub type SphericalPositionRateOptionalType = Option<SphericalPositionRateType>;

pub type EllipsoidalPositionRateOptionalType = Option<EllipsoidalPositionRateType>;

pub type LinearVelocityOptionalType = Option<LinearVelocityType>;

pub type LinearVelocityListType = Vec<LinearVelocityType>;

pub type CartesianAngularVelocityOptionalType = Option<CartesianAngularVelocityType>;

pub type AngularVelocityOptionalType = Option<AngularVelocityType>;

pub type AngularVelocityListType = Vec<AngularVelocityType>;

pub type CartesianLinearAccelerationOptionalType = Option<CartesianLinearAccelerationType>;

pub type LinearAccelerationOptionalType = Option<LinearAccelerationType>;

pub type LinearAccelerationListType = Vec<LinearAccelerationType>;

pub type CartesianAngularAccelerationOptionalType = Option<CartesianAngularAccelerationType>;

pub type AngularAccelerationOptionalType = Option<AngularAccelerationType>;

pub type AngularAccelerationListType = Vec<AngularAccelerationType>;

pub type CoordinateTransformationListType = Vec<CoordinateTransformationType>;

pub type MultiPositionOptionalType = Option<MultiPositionType>;

pub type MultiPositionListType = Vec<MultiPositionType>;

pub type PixelPoint2DOptionalType = Option<PixelPoint2DType>;

pub type PixelPoint2DListType = Vec<PixelPoint2DType>;

pub type PixelOffsetOptionalType = Option<PixelOffsetType>;

pub type PixelOffsetListType = Vec<PixelOffsetType>;

pub type PixelRectSizeOptionalType = Option<PixelRectSizeType>;

pub type PixelRegionOptionalType = Option<PixelRegionType>;

pub type DegreeOffsetOptionalType = Option<DegreeOffsetType>;

pub type DegreeOffsetListType = Vec<DegreeOffsetType>;

pub type DegreeRectSizeOptionalType = Option<DegreeRectSizeType>;

pub type DegreeRegionOptionalType = Option<DegreeRegionType>;

pub type ImageOptionalType = Option<ImageType>;

pub type ColourSchemeOptionalType = Option<colour_scheme::Type>;

pub type ColourStyleOptionalType = Option<ColourStyleType>;

pub type CartesianDimensionsOptionalType = Option<CartesianDimensionsType>;

pub type SphericalDimensionsOptionalType = Option<SphericalDimensionsType>;

pub type ObjectDimensionsOptionalType = Option<ObjectDimensionsType>;

pub type ObjectDimensionsListType = Vec<ObjectDimensionsType>;

pub type ObjectRelationListType = Vec<ObjectRelationType>;

pub type HorizontalDirectionOptionalType = Option<horizontal_direction::Type>;

pub type VerticalDirectionOptionalType = Option<vertical_direction::Type>;

pub type TemperatureKelvinsSelectionOptionalType = Option<TemperatureKelvinsSelectionType>;

pub type PressurePascalsSelectionOptionalType = Option<PressurePascalsSelectionType>;

pub type PercentSelectionOptionalType = Option<PercentSelectionType>;

pub type LinearVelocitySelectionOptionalType = Option<LinearVelocitySelectionType>;

pub type DistanceMetersSelectionOptionalType = Option<DistanceMetersSelectionType>;

pub type EulerAttitudeSelectionOptionalType = Option<EulerAttitudeSelectionType>;

pub type AngleRateDegreesPerSecSelectionOptionalType = Option<AngleRateDegreesPerSecSelectionType>;

pub type SphericalPositionRateSelectionOptionalType = Option<SphericalPositionRateSelectionType>;

pub type EncryptionOptionalType = Option<EncryptionType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ObjectClassificationType {
    #[serde(rename = "Category")]
    pub category: u32,
    #[serde(rename = "AbstractionLayer")]
    pub abstraction_layer: String,
    #[serde(rename = "Confidence")]
    pub confidence: PercentOptionalType,
    #[serde(rename = "Priority")]
    pub priority: DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PropertyType {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "StrValue")]
    pub str_value: String,
    #[serde(rename = "DoubleValue")]
    pub double_value: DoubleOptionalType,
    #[serde(rename = "LongValue")]
    pub long_value: LongOptionalType,
    #[serde(rename = "AccessMode")]
    pub access_mode: property_access_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct OperationModeType {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "EnumeratedValue")]
    pub enumerated_value: OperationModeStateOptionalType,
    #[serde(rename = "IntegerValue")]
    pub integer_value: LongOptionalType,
    #[serde(rename = "TextualValue")]
    pub textual_value: StringOptionalType,
    #[serde(rename = "TransitionState")]
    pub transition_state: ModeTransitionOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct OperationFaultType {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "EnumeratedValue")]
    pub enumerated_value: OperationFaultStateOptionalType,
    #[serde(rename = "IntegerValue")]
    pub integer_value: LongOptionalType,
    #[serde(rename = "TextualValue")]
    pub textual_value: StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModeTransitionInfoType {
    #[serde(rename = "LastState")]
    pub last_state: OperationModeOptionalType,
    #[serde(rename = "RequestedState")]
    pub requested_state: OperationModeOptionalType,
    #[serde(rename = "Errors")]
    pub errors: OperationFaultListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct OperationStatusType {
    #[serde(rename = "Mode")]
    pub mode: OperationModeOptionalType,
    #[serde(rename = "ModeTransitionInfo")]
    pub mode_transition_info: ModeTransitionInfoOptionalType,
    #[serde(rename = "PermittedModeTransitionList")]
    pub permitted_mode_transition_list: OperationModeListType,
    #[serde(rename = "SubmodeList")]
    pub submode_list: OperationModeListType,
    #[serde(rename = "Faults")]
    pub faults: OperationFaultListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TimeType {
    #[serde(rename = "Seconds")]
    pub seconds: i64,
    #[serde(rename = "Nanoseconds")]
    pub nanoseconds: i32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UtcType {
    #[serde(rename = "UtcString")]
    pub utc_string: StringOptionalType,
    #[serde(rename = "UnixTime")]
    pub unix_time: UnixTimeOptionalType,
    #[serde(rename = "UtcOffsetMinutes")]
    pub utc_offset_minutes: LongOptionalType,
    #[serde(rename = "TimeStamp")]
    pub time_stamp: TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DurationType {
    #[serde(rename = "DurationString")]
    pub duration_string: StringOptionalType,
    #[serde(rename = "DurationNumeric")]
    pub duration_numeric: TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TimeIntervalType {
    #[serde(rename = "StartTime")]
    pub start_time: TimeType,
    #[serde(rename = "StopTime")]
    pub stop_time: TimeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisDirectionType {
    #[serde(rename = "X")]
    pub x: f64,
    #[serde(rename = "Y")]
    pub y: f64,
    #[serde(rename = "Z")]
    pub z: f64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisScalarType {
    #[serde(rename = "Vector")]
    pub vector: AxisDirectionType,
    #[serde(rename = "Scalar")]
    pub scalar: f64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MagneticFluxDensityType {
    #[serde(rename = "X")]
    pub x: MagneticFluxDensityTeslasType,
    #[serde(rename = "Y")]
    pub y: MagneticFluxDensityTeslasType,
    #[serde(rename = "Z")]
    pub z: MagneticFluxDensityTeslasType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UncertaintyType {
    #[serde(rename = "StandardDeviation")]
    pub standard_deviation: DoubleListType,
    #[serde(rename = "EstimatedStandardError")]
    pub estimated_standard_error: DoubleListType,
    #[serde(rename = "Covariance")]
    pub covariance: DoubleMatrixType,
    #[serde(rename = "ConfidenceRegion")]
    pub confidence_region: DoubleMatrixType,
    #[serde(rename = "ConfidenceLevel")]
    pub confidence_level: DoubleListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CartesianPositionType {
    #[serde(rename = "X")]
    pub x: DistanceMetersType,
    #[serde(rename = "Y")]
    pub y: DistanceMetersType,
    #[serde(rename = "Z")]
    pub z: DistanceMetersType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SphericalPositionType {
    #[serde(rename = "Azimuth")]
    pub azimuth: AngleDegreesType,
    #[serde(rename = "Elevation")]
    pub elevation: AngleDegreesType,
    #[serde(rename = "Range")]
    pub range: DistanceMetersOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct EllipsoidalPositionType {
    #[serde(rename = "Latitude")]
    pub latitude: AngleDegreesType,
    #[serde(rename = "Longitude")]
    pub longitude: AngleDegreesType,
    #[serde(rename = "Altitude")]
    pub altitude: DistanceMetersOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PositionType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianPositionOptionalType,
    #[serde(rename = "Spherical")]
    pub spherical: SphericalPositionOptionalType,
    #[serde(rename = "Ellipsoidal")]
    pub ellipsoidal: EllipsoidalPositionOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct EulerAttitudeType {
    #[serde(rename = "Roll")]
    pub roll: AngleDegreesOptionalType,
    #[serde(rename = "Pitch")]
    pub pitch: AngleDegreesOptionalType,
    #[serde(rename = "Yaw")]
    pub yaw: AngleDegreesOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AttitudeType {
    #[serde(rename = "Euler")]
    pub euler: EulerAttitudeOptionalType,
    #[serde(rename = "AxisScalar")]
    pub axis_scalar: AxisScalarOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CartesianLinearVelocityType {
    #[serde(rename = "X")]
    pub x: SpeedMetersPerSecType,
    #[serde(rename = "Y")]
    pub y: SpeedMetersPerSecType,
    #[serde(rename = "Z")]
    pub z: SpeedMetersPerSecType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SphericalLinearVelocityType {
    #[serde(rename = "Azimuth")]
    pub azimuth: AngleDegreesOptionalType,
    #[serde(rename = "Elevation")]
    pub elevation: AngleDegreesOptionalType,
    #[serde(rename = "Speed")]
    pub speed: SpeedMetersPerSecType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SphericalPositionRateType {
    #[serde(rename = "AzimuthRate")]
    pub azimuth_rate: AngleRateDegreesPerSecType,
    #[serde(rename = "ElevationRate")]
    pub elevation_rate: AngleRateDegreesPerSecType,
    #[serde(rename = "RangeRate")]
    pub range_rate: SpeedMetersPerSecOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct EllipsoidalPositionRateType {
    #[serde(rename = "LatitudeRate")]
    pub latitude_rate: AngleRateDegreesPerSecType,
    #[serde(rename = "LongitudeRate")]
    pub longitude_rate: AngleRateDegreesPerSecType,
    #[serde(rename = "AltitudeRate")]
    pub altitude_rate: SpeedMetersPerSecOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LinearVelocityType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianLinearVelocityOptionalType,
    #[serde(rename = "Spherical")]
    pub spherical: SphericalLinearVelocityOptionalType,
    #[serde(rename = "SphericalPositionRate")]
    pub spherical_position_rate: SphericalPositionRateOptionalType,
    #[serde(rename = "EllipsoidalPositionRate")]
    pub ellipsoidal_position_rate: EllipsoidalPositionRateOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CartesianAngularVelocityType {
    #[serde(rename = "X")]
    pub x: AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "Y")]
    pub y: AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "Z")]
    pub z: AngleRateDegreesPerSecOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AngularVelocityType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianAngularVelocityOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CartesianLinearAccelerationType {
    #[serde(rename = "X")]
    pub x: AccelerationMetersPerSecPerSecType,
    #[serde(rename = "Y")]
    pub y: AccelerationMetersPerSecPerSecType,
    #[serde(rename = "Z")]
    pub z: AccelerationMetersPerSecPerSecType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LinearAccelerationType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianLinearAccelerationOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CartesianAngularAccelerationType {
    #[serde(rename = "X")]
    pub x: AngularAccelerationDegreesPerSecPerSecOptionalType,
    #[serde(rename = "Y")]
    pub y: AngularAccelerationDegreesPerSecPerSecOptionalType,
    #[serde(rename = "Z")]
    pub z: AngularAccelerationDegreesPerSecPerSecOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AngularAccelerationType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianAngularAccelerationOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CoordinateTransformationType {
    #[serde(rename = "Target")]
    pub target: String,
    #[serde(rename = "Source")]
    pub source: StringOptionalType,
    #[serde(rename = "TransformationFromSourceToTarget")]
    pub transformation_from_source_to_target: DoubleMatrixType,
    #[serde(rename = "SourcePositionRelativeToTarget")]
    pub source_position_relative_to_target: CartesianPositionOptionalType,
    #[serde(rename = "SourceAttitudeRelativeToTarget")]
    pub source_attitude_relative_to_target: EulerAttitudeOptionalType,
    #[serde(rename = "Timestamp")]
    pub timestamp: TimeOptionalType,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MultiPositionType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianPositionListType,
    #[serde(rename = "Spherical")]
    pub spherical: SphericalPositionListType,
    #[serde(rename = "Ellipsoidal")]
    pub ellipsoidal: EllipsoidalPositionListType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
    #[serde(rename = "StorageMode")]
    pub storage_mode: storage_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PixelPoint2DType {
    #[serde(rename = "X")]
    pub x: u32,
    #[serde(rename = "Y")]
    pub y: u32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PixelOffsetType {
    #[serde(rename = "X")]
    pub x: i32,
    #[serde(rename = "Y")]
    pub y: i32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PixelRectSizeType {
    #[serde(rename = "Width")]
    pub width: u32,
    #[serde(rename = "Height")]
    pub height: u32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PixelRegionType {
    #[serde(rename = "Offset")]
    pub offset: PixelOffsetType,
    #[serde(rename = "Size")]
    pub size: PixelRectSizeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DegreeOffsetType {
    #[serde(rename = "Azimuth")]
    pub azimuth: AngleDegreesType,
    #[serde(rename = "Elevation")]
    pub elevation: AngleDegreesType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DegreeRectSizeType {
    #[serde(rename = "Width")]
    pub width: AngleDegreesType,
    #[serde(rename = "Height")]
    pub height: AngleDegreesType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DegreeRegionType {
    #[serde(rename = "Offset")]
    pub offset: DegreeOffsetType,
    #[serde(rename = "Size")]
    pub size: DegreeRectSizeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageRegionType {
    #[serde(rename = "RegionPixels")]
    pub region_pixels: PixelRegionOptionalType,
    #[serde(rename = "RegionDegrees")]
    pub region_degrees: DegreeRegionOptionalType,
    #[serde(rename = "RotationAngle")]
    pub rotation_angle: AngleDegreesOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageType {
    #[serde(rename = "Format")]
    pub format: image_kind::Type,
    #[serde(rename = "Size")]
    pub size: PixelRectSizeOptionalType,
    #[serde(rename = "Data")]
    pub data: ByteSeqType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ColourStyleType {
    #[serde(rename = "ColourScheme")]
    pub colour_scheme: ColourSchemeOptionalType,
    #[serde(rename = "ColourCode")]
    pub colour_code: ULongOptionalType,
    #[serde(rename = "Opacity")]
    pub opacity: PercentOptionalType,
    #[serde(rename = "Contrast")]
    pub contrast: PercentOptionalType,
    #[serde(rename = "Brightness")]
    pub brightness: PercentOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CartesianDimensionsType {
    #[serde(rename = "Width")]
    pub width: DistanceMetersOptionalType,
    #[serde(rename = "Height")]
    pub height: DistanceMetersOptionalType,
    #[serde(rename = "Length")]
    pub length: DistanceMetersOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SphericalDimensionsType {
    #[serde(rename = "Width")]
    pub width: AngleDegreesOptionalType,
    #[serde(rename = "Height")]
    pub height: AngleDegreesOptionalType,
    #[serde(rename = "Length")]
    pub length: DistanceMetersOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ObjectDimensionsType {
    #[serde(rename = "Cartesian")]
    pub cartesian: CartesianDimensionsOptionalType,
    #[serde(rename = "Spherical")]
    pub spherical: SphericalDimensionsOptionalType,
    #[serde(rename = "Pixels")]
    pub pixels: PixelRectSizeOptionalType,
    #[serde(rename = "RotationAngle")]
    pub rotation_angle: AngleDegreesOptionalType,
    #[serde(rename = "Uncertainty")]
    pub uncertainty: UncertaintyOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ObjectRelationType {
    #[serde(rename = "Id")]
    pub id: ObjectIdType,
    #[serde(rename = "RelationKind")]
    pub relation_kind: object_relation_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TemperatureKelvinsSelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: TemperatureKelvinsOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: TemperatureKelvinsOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: TemperatureKelvinsOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PressurePascalsSelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: PressurePascalsOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: PressurePascalsOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: PressurePascalsOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PercentSelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: PercentOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: PercentOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: PercentOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LinearVelocitySelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: LinearVelocityOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: LinearVelocityOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: LinearVelocityOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DistanceMetersSelectionType {
    #[serde(rename = "SourceId")]
    pub source_id: StringOptionalType,
    #[serde(rename = "DefaultValue")]
    pub default_value: DistanceMetersOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: DistanceMetersOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: DistanceMetersOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct EulerAttitudeSelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: EulerAttitudeOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: EulerAttitudeOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: EulerAttitudeOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AngleRateDegreesPerSecSelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SphericalPositionRateSelectionType {
    #[serde(rename = "DefaultValue")]
    pub default_value: SphericalPositionRateOptionalType,
    #[serde(rename = "ManualValue")]
    pub manual_value: SphericalPositionRateOptionalType,
    #[serde(rename = "AutoValue")]
    pub auto_value: SphericalPositionRateOptionalType,
    #[serde(rename = "ActiveSelection")]
    pub active_selection: selected_value_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct EncryptionType {
    #[serde(rename = "Algorithm")]
    pub algorithm: String,
    #[serde(rename = "Token")]
    pub token: ByteSeqType,
    #[serde(rename = "Aad")]
    pub aad: ByteSeqType,
    #[serde(rename = "Iv")]
    pub iv: ByteSeqType,
    #[serde(rename = "Mac")]
    pub mac: ByteSeqType,
    #[serde(rename = "Nounce")]
    pub nounce: ByteSeqType,
}

pub mod general_status {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Not_Supported")]
        Not_Supported,
        #[serde(rename = "Enabled")]
        Enabled,
        #[serde(rename = "Disabled")]
        Disabled,
    }

}

pub mod property_access_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Read_Only")]
        Read_Only,
        #[serde(rename = "Write_Only")]
        Write_Only,
        #[serde(rename = "Read_Write")]
        Read_Write,
    }

}

pub mod operation_mode_state_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Off")]
        Off,
        #[serde(rename = "On")]
        On,
        #[serde(rename = "Standby")]
        Standby,
        #[serde(rename = "Init")]
        Init,
        #[serde(rename = "Shutdown")]
        Shutdown,
        #[serde(rename = "Normal")]
        Normal,
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "Auto")]
        Auto,
        #[serde(rename = "Calibrating")]
        Calibrating,
        #[serde(rename = "Maintenance")]
        Maintenance,
        #[serde(rename = "Simulation")]
        Simulation,
    }

}

pub mod mode_transition_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "In_Progress")]
        In_Progress,
        #[serde(rename = "Complete")]
        Complete,
        #[serde(rename = "Error")]
        Error,
    }

}

pub mod operation_fault_state_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Init_Failure")]
        Init_Failure,
        #[serde(rename = "Warning")]
        Warning,
        #[serde(rename = "Failure")]
        Failure,
        #[serde(rename = "Critical")]
        Critical,
        #[serde(rename = "Fatal")]
        Fatal,
    }

}

pub mod storage_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Not_Persistent")]
        Not_Persistent,
        #[serde(rename = "Persistent")]
        Persistent,
    }

}

pub mod optical_sensor_mode {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Infrared")]
        Infrared,
        #[serde(rename = "Daylight")]
        Daylight,
    }

}

pub mod zoom_factor {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Zoom_0_25x")]
        Zoom_0_25x,
        #[serde(rename = "Zoom_0_5x")]
        Zoom_0_5x,
        #[serde(rename = "Zoom_1x")]
        Zoom_1x,
        #[serde(rename = "Zoom_2x")]
        Zoom_2x,
    }

}

pub mod image_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Bin")]
        Bin,
        #[serde(rename = "Raw8")]
        Raw8,
        #[serde(rename = "Bmp")]
        Bmp,
        #[serde(rename = "Png")]
        Png,
        #[serde(rename = "Jpeg")]
        Jpeg,
        #[serde(rename = "Svg")]
        Svg,
    }

}

pub mod colour_scheme {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Black_White")]
        Black_White,
        #[serde(rename = "Grayscale")]
        Grayscale,
        #[serde(rename = "RGB")]
        RGB,
        #[serde(rename = "HSL")]
        HSL,
        #[serde(rename = "HSV")]
        HSV,
    }

}

pub mod object_relation_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "DerivedFrom")]
        DerivedFrom,
        #[serde(rename = "Associated")]
        Associated,
        #[serde(rename = "PointOfOrigin")]
        PointOfOrigin,
        #[serde(rename = "PointOfDestination")]
        PointOfDestination,
        #[serde(rename = "ClusterComponent")]
        ClusterComponent,
        #[serde(rename = "TrackSplit")]
        TrackSplit,
        #[serde(rename = "TrackMerge")]
        TrackMerge,
        #[serde(rename = "Duplicate")]
        Duplicate,
    }

}

pub mod availability {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "Available")]
        Available,
        #[serde(rename = "Reduced_Performance")]
        Reduced_Performance,
        #[serde(rename = "Not_Available")]
        Not_Available,
    }

}

pub mod horizontal_direction {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Right")]
        Right,
        #[serde(rename = "Left")]
        Left,
    }

}

pub mod vertical_direction {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Up")]
        Up,
        #[serde(rename = "Down")]
        Down,
    }

}

pub mod selected_value_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Fallback")]
        Fallback,
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "Auto")]
        Auto,
    }

}

