// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type CoordinateFrameDatumSupportListType = Vec<CoordinateFrameDatumSupportType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CoordinateFrameDatumSupportType {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "SupportedCoordinateFrame")]
    pub supported_coordinate_frame: String,
    #[serde(rename = "DataOutputFrequency")]
    pub data_output_frequency: crate::common::FrequencyHertzOptionalType,
    #[serde(rename = "AccessMode")]
    pub access_mode: crate::common::property_access_kind::Type,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CoordinateFrameSettingsType {
    #[serde(rename = "SupportedPositionList")]
    pub supported_position_list: CoordinateFrameDatumSupportListType,
    #[serde(rename = "SupportedAttitudeList")]
    pub supported_attitude_list: CoordinateFrameDatumSupportListType,
    #[serde(rename = "SupportedLinearVelocityList")]
    pub supported_linear_velocity_list: CoordinateFrameDatumSupportListType,
    #[serde(rename = "SupportedAngularVelocityList")]
    pub supported_angular_velocity_list: CoordinateFrameDatumSupportListType,
    #[serde(rename = "SupportedLinearAccelerationList")]
    pub supported_linear_acceleration_list: CoordinateFrameDatumSupportListType,
    #[serde(rename = "SupportedAngularAccelerationList")]
    pub supported_angular_acceleration_list: CoordinateFrameDatumSupportListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CoordinateFrameStatusType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
}

