// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type HardwareInfoListType = Vec<HardwareInfoType>;

pub type SoftwareVersionListType = Vec<SoftwareVersionType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct HardwareInfoType {
    #[serde(rename = "ModuleName")]
    pub module_name: String,
    #[serde(rename = "HardwareVersion")]
    pub hardware_version: String,
    #[serde(rename = "HardwarePartNumber")]
    pub hardware_part_number: String,
    #[serde(rename = "HardwareSerialNumber")]
    pub hardware_serial_number: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SoftwareVersionType {
    #[serde(rename = "ModuleName")]
    pub module_name: String,
    #[serde(rename = "ChildModuleNames")]
    pub child_module_names: crate::common::StringListType,
    #[serde(rename = "Major")]
    pub major: u32,
    #[serde(rename = "Minor")]
    pub minor: u32,
    #[serde(rename = "Patch")]
    pub patch: u32,
    #[serde(rename = "PartNumber")]
    pub part_number: String,
    #[serde(rename = "Tag")]
    pub tag: String,
    #[serde(rename = "VcsId")]
    pub vcs_id: String,
    #[serde(rename = "MaterialRevision")]
    pub material_revision: String,
    #[serde(rename = "BuildDate")]
    pub build_date: crate::common::TimeOptionalType,
    #[serde(rename = "CommitDate")]
    pub commit_date: crate::common::TimeOptionalType,
    #[serde(rename = "Checksum")]
    pub checksum: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DeviceSettingsType {
    #[serde(rename = "DeviceName")]
    pub device_name: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "HwInfoList")]
    pub hw_info_list: HardwareInfoListType,
    #[serde(rename = "SwVersionList")]
    pub sw_version_list: SoftwareVersionListType,
    #[serde(rename = "IsSetDeviceModeSupported")]
    pub is_set_device_mode_supported: bool,
    #[serde(rename = "SupportedOperationStatusList")]
    pub supported_operation_status_list: crate::common::OperationStatusListType,
    #[serde(rename = "IsShutdownDeviceSupported")]
    pub is_shutdown_device_supported: bool,
    #[serde(rename = "ShutdownDurationSec")]
    pub shutdown_duration_sec: crate::common::ULongOptionalType,
    #[serde(rename = "IsRestartDeviceSupported")]
    pub is_restart_device_supported: bool,
    #[serde(rename = "RestartDurationSec")]
    pub restart_duration_sec: crate::common::ULongOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DeviceStatusType {
    #[serde(rename = "IsEnabled")]
    pub is_enabled: bool,
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
}

