// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type DialogueCategoryOptionalType = Option<dialogue_category_kind::Type>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InputChoiceType {
    #[serde(rename = "Text")]
    pub text: String,
    #[serde(rename = "InputSelectionList")]
    pub input_selection_list: crate::common::StringListType,
    #[serde(rename = "Category")]
    pub category: dialogue_category_kind::Type,
    #[serde(rename = "InitiatedByClientId")]
    pub initiated_by_client_id: String,
}

pub mod dialogue_category_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Off")]
        Off,
        #[serde(rename = "Trace")]
        Trace,
        #[serde(rename = "Info")]
        Info,
        #[serde(rename = "Warning")]
        Warning,
        #[serde(rename = "Error")]
        Error,
        #[serde(rename = "Question")]
        Question,
    }

}

