// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ErrorEntryType {
    #[serde(rename = "Timestamp")]
    pub timestamp: crate::common::TimeType,
    #[serde(rename = "ErrorCode")]
    pub error_code: String,
    #[serde(rename = "ErrorClass")]
    pub error_class: error_class_kind::Type,
    #[serde(rename = "ErrorSource")]
    pub error_source: String,
    #[serde(rename = "ErrorMethod")]
    pub error_method: error_identification_method_kind::Type,
    #[serde(rename = "ShortText")]
    pub short_text: String,
    #[serde(rename = "LongText")]
    pub long_text: String,
}

pub mod error_class_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Warning")]
        Warning,
        #[serde(rename = "Reduced_Performance_Error")]
        Reduced_Performance_Error,
        #[serde(rename = "Fatal_Error")]
        Fatal_Error,
        #[serde(rename = "OK")]
        OK,
    }

}

pub mod error_identification_method_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "PBIT")]
        PBIT,
        #[serde(rename = "CBIT")]
        CBIT,
        #[serde(rename = "FP")]
        FP,
        #[serde(rename = "FL")]
        FL,
    }

}

