// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type FileTransferInfoOptionalType = Option<FileTransferInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FileTransferInfoType {
    #[serde(rename = "SourceFileUrl")]
    pub source_file_url: String,
    #[serde(rename = "TargetFileUrl")]
    pub target_file_url: String,
    #[serde(rename = "Offset")]
    pub offset: crate::common::ULongLongOptionalType,
    #[serde(rename = "Size")]
    pub size: crate::common::ULongLongOptionalType,
    #[serde(rename = "EncryptionInfo")]
    pub encryption_info: crate::common::EncryptionOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FileTransferStatusType {
    #[serde(rename = "TransferStatus")]
    pub transfer_status: transfer_status_kind::Type,
    #[serde(rename = "TransferStatusDescription")]
    pub transfer_status_description: String,
    #[serde(rename = "CurrentBytes")]
    pub current_bytes: crate::common::ULongLongOptionalType,
    #[serde(rename = "TotalBytes")]
    pub total_bytes: crate::common::ULongLongOptionalType,
}

pub mod transfer_status_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "In_Progress")]
        In_Progress,
        #[serde(rename = "Waiting")]
        Waiting,
        #[serde(rename = "Paused")]
        Paused,
        #[serde(rename = "Failed")]
        Failed,
        #[serde(rename = "Success")]
        Success,
    }

}

