// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InputOutputData {
    #[serde(rename = "Data")]
    pub data: crate::common::ByteSeqType,
    #[serde(rename = "Timestamp")]
    pub timestamp: crate::common::TimeOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InputOutputSettings {
    #[serde(rename = "InterfaceName")]
    pub interface_name: String,
    #[serde(rename = "InterfaceDescription")]
    pub interface_description: String,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InputOutputConfiguration {
    #[serde(rename = "Override")]
    pub r#override: bool,
    #[serde(rename = "InterfaceConfiguration")]
    pub interface_configuration: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InputOutputStatus {
    #[serde(rename = "IsOpen")]
    pub is_open: bool,
    #[serde(rename = "ActiveConfigurationSources")]
    pub active_configuration_sources: crate::common::StringListType,
    #[serde(rename = "ActiveConfiguration")]
    pub active_configuration: InputOutputConfiguration,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

