// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ButtonInfoListType = Vec<ButtonInfoType>;

pub type AxisInfoListType = Vec<AxisInfoType>;

pub type DeviceInfoListType = Vec<DeviceInfoType>;

pub type IncrementEncoderInfoListType = Vec<IncrementEncoderInfoType>;

pub type ValueInputInfoListType = Vec<ValueInputInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ButtonInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "DeviceId")]
    pub device_id: crate::common::LongLongOptionalType,
    #[serde(rename = "HardwareAddress")]
    pub hardware_address: crate::common::LongLongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "DeviceId")]
    pub device_id: crate::common::LongLongOptionalType,
    #[serde(rename = "HardwareAddress")]
    pub hardware_address: crate::common::LongLongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct DeviceInfoType {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "DeviceId")]
    pub device_id: crate::common::LongLongOptionalType,
    #[serde(rename = "HardwareAddress")]
    pub hardware_address: crate::common::LongLongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct IncrementEncoderInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "DeviceId")]
    pub device_id: crate::common::LongLongOptionalType,
    #[serde(rename = "HardwareAddress")]
    pub hardware_address: crate::common::LongLongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ValueInputInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Description")]
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct JoystickSettingsType {
    #[serde(rename = "Axes")]
    pub axes: AxisInfoListType,
    #[serde(rename = "Buttons")]
    pub buttons: ButtonInfoListType,
    #[serde(rename = "IncrementEncoders")]
    pub increment_encoders: IncrementEncoderInfoListType,
    #[serde(rename = "ValueInputs")]
    pub value_inputs: ValueInputInfoListType,
    #[serde(rename = "DeviceInfo")]
    pub device_info: DeviceInfoType,
    #[serde(rename = "IsConfigJoystickCurveSupported")]
    pub is_config_joystick_curve_supported: bool,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

