// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CoordInputSettingsType {
    #[serde(rename = "IsCursorPositionSupported")]
    pub is_cursor_position_supported: bool,
    #[serde(rename = "IsClickSupported")]
    pub is_click_supported: bool,
}

