// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ButtonDisplayInfoListType = Vec<ButtonDisplayInfoType>;

pub type LedLightModeActionListType = Vec<LedLightModeActionType>;

pub type AxisDisplayInfoListType = Vec<AxisDisplayInfoType>;

pub type LedDisplayInfoListType = Vec<LedDisplayInfoType>;

pub type ValueInputInfoListType = Vec<ValueInputInfoType>;

pub type MenuInfoListType = Vec<MenuInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ButtonDisplayInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Label")]
    pub label: String,
    #[serde(rename = "Image")]
    pub image: crate::common::ImageType,
    #[serde(rename = "IsEnabled")]
    pub is_enabled: bool,
    #[serde(rename = "IsHighlighted")]
    pub is_highlighted: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LedLightModeActionType {
    #[serde(rename = "LedLightOn")]
    pub led_light_on: bool,
    #[serde(rename = "RgbColorCode")]
    pub rgb_color_code: crate::common::ULongOptionalType,
    #[serde(rename = "durationInMilliseconds")]
    pub duration_in_milliseconds: crate::common::ULongOptionalType,
    #[serde(rename = "Brightness")]
    pub brightness: crate::common::PercentOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LedLightModeType {
    #[serde(rename = "Actions")]
    pub actions: LedLightModeActionListType,
    #[serde(rename = "RepeatCount")]
    pub repeat_count: crate::common::ULongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisDisplayInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "NegativeLabel")]
    pub negative_label: String,
    #[serde(rename = "NegativeImage")]
    pub negative_image: crate::common::ImageType,
    #[serde(rename = "PositiveLabel")]
    pub positive_label: String,
    #[serde(rename = "PositiveImage")]
    pub positive_image: crate::common::ImageType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LedDisplayInfoType {
    #[serde(rename = "Index")]
    pub index: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Label")]
    pub label: String,
    #[serde(rename = "LedLightMode")]
    pub led_light_mode: LedLightModeType,
    #[serde(rename = "SupportedRgbColorCodesList")]
    pub supported_rgb_color_codes_list: crate::common::ULongListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ValueInputInfoType {
    #[serde(rename = "ValueInputIndex")]
    pub value_input_index: u32,
    #[serde(rename = "Label")]
    pub label: String,
    #[serde(rename = "IsEnabled")]
    pub is_enabled: bool,
    #[serde(rename = "ValueInputMode")]
    pub value_input_mode: crate::common::PropertyOptionalType,
    #[serde(rename = "DefaultValue")]
    pub default_value: crate::common::PropertyOptionalType,
    #[serde(rename = "MinValue")]
    pub min_value: crate::common::PropertyOptionalType,
    #[serde(rename = "MaxValue")]
    pub max_value: crate::common::PropertyOptionalType,
    #[serde(rename = "PresetList")]
    pub preset_list: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MenuInfoType {
    #[serde(rename = "MenuIndex")]
    pub menu_index: u32,
    #[serde(rename = "Label")]
    pub label: String,
    #[serde(rename = "IsEnabled")]
    pub is_enabled: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct HidInfoType {
    #[serde(rename = "Axes")]
    pub axes: AxisDisplayInfoListType,
    #[serde(rename = "Buttons")]
    pub buttons: ButtonDisplayInfoListType,
    #[serde(rename = "Leds")]
    pub leds: LedDisplayInfoListType,
    #[serde(rename = "ValueInputs")]
    pub value_inputs: ValueInputInfoListType,
    #[serde(rename = "Menus")]
    pub menus: MenuInfoListType,
    #[serde(rename = "BackgroundIlluminationLevel")]
    pub background_illumination_level: crate::common::PercentOptionalType,
    #[serde(rename = "IsBlackoutModeEnabled")]
    pub is_blackout_mode_enabled: bool,
}

