// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type RequestedAxisListType = Vec<RequestedAxisType>;

pub type AssignedAxisListType = Vec<AssignedAxisType>;

pub type RequestedValueInputListType = Vec<RequestedValueInputType>;

pub type AssignedValueInputListType = Vec<AssignedValueInputType>;

pub type RequestedButtonListType = Vec<RequestedButtonType>;

pub type AssignedButtonListType = Vec<AssignedButtonType>;

pub type RequestedMenuListType = Vec<RequestedMenuType>;

pub type AssignedMenuListType = Vec<AssignedMenuType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RequestedAxisType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "Description")]
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AssignedAxisType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "AxisIndex")]
    pub axis_index: u32,
    #[serde(rename = "ServiceName")]
    pub service_name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RequestedValueInputType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "ValueInputType")]
    pub value_input_type: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AssignedValueInputType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "ValueInputIndex")]
    pub value_input_index: u32,
    #[serde(rename = "ServiceName")]
    pub service_name: String,
    #[serde(rename = "ValueInputType")]
    pub value_input_type: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RequestedButtonType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "ButtonType")]
    pub button_type: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AssignedButtonType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "ButtonIndex")]
    pub button_index: u32,
    #[serde(rename = "ButtonType")]
    pub button_type: String,
    #[serde(rename = "ServiceName")]
    pub service_name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RequestedMenuType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "ChildIds")]
    pub child_ids: crate::common::ULongListType,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "MenuType")]
    pub menu_type: String,
    #[serde(rename = "ValueInputList")]
    pub value_input_list: RequestedValueInputListType,
    #[serde(rename = "ButtonList")]
    pub button_list: RequestedButtonListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AssignedMenuType {
    #[serde(rename = "RequestedId")]
    pub requested_id: u32,
    #[serde(rename = "ChildIds")]
    pub child_ids: crate::common::ULongListType,
    #[serde(rename = "MenuId")]
    pub menu_id: u32,
    #[serde(rename = "MenuType")]
    pub menu_type: String,
    #[serde(rename = "ServiceName")]
    pub service_name: String,
    #[serde(rename = "ValueInputList")]
    pub value_input_list: AssignedValueInputListType,
    #[serde(rename = "ButtonList")]
    pub button_list: AssignedButtonListType,
}

