// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type FunctionalAreaOptionalType = Option<functional_area_kind::Type>;

pub type RestartOnFailureOptionalType = Option<RestartOnFailureType>;

pub type ApplicationDescriptionListType = Vec<ApplicationDescriptionType>;

pub type ViewRuleListType = Vec<ViewRuleType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RestartOnFailureType {
    #[serde(rename = "Enabled")]
    pub enabled: bool,
    #[serde(rename = "DelayInMilliseconds")]
    pub delay_in_milliseconds: i32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ApplicationDescriptionType {
    #[serde(rename = "AppId")]
    pub app_id: String,
    #[serde(rename = "Enabled")]
    pub enabled: bool,
    #[serde(rename = "Command")]
    pub command: String,
    #[serde(rename = "Parameters")]
    pub parameters: crate::common::StringListType,
    #[serde(rename = "WorkingDirectory")]
    pub working_directory: crate::common::StringOptionalType,
    #[serde(rename = "Name")]
    pub name: crate::common::StringOptionalType,
    #[serde(rename = "AssociatedFunctionalArea")]
    pub associated_functional_area: FunctionalAreaOptionalType,
    #[serde(rename = "RestartOnFailure")]
    pub restart_on_failure: RestartOnFailureOptionalType,
    #[serde(rename = "EnvironmentVariables")]
    pub environment_variables: crate::common::PropertyListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ApplicationStateType {
    #[serde(rename = "IsInstalled")]
    pub is_installed: bool,
    #[serde(rename = "IsRunning")]
    pub is_running: bool,
    #[serde(rename = "IsActive")]
    pub is_active: crate::common::BooleanOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ViewRuleType {
    #[serde(rename = "Priority")]
    pub priority: i32,
    #[serde(rename = "Enabled")]
    pub enabled: bool,
    #[serde(rename = "UiRegionName")]
    pub ui_region_name: String,
    #[serde(rename = "UiRegionAlwaysOnTop")]
    pub ui_region_always_on_top: view_always_on_top_kind::Type,
    #[serde(rename = "UiTitleBar")]
    pub ui_title_bar: crate::common::BooleanOptionalType,
    #[serde(rename = "UiRegionLeft")]
    pub ui_region_left: crate::common::LongOptionalType,
    #[serde(rename = "UiRegionTop")]
    pub ui_region_top: crate::common::LongOptionalType,
    #[serde(rename = "UiRegionRight")]
    pub ui_region_right: crate::common::LongOptionalType,
    #[serde(rename = "UiRegionBottom")]
    pub ui_region_bottom: crate::common::LongOptionalType,
    #[serde(rename = "UiFocus")]
    pub ui_focus: view_focus_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ViewDescriptionType {
    #[serde(rename = "Enabled")]
    pub enabled: bool,
    #[serde(rename = "ViewRules")]
    pub view_rules: ViewRuleListType,
}

pub mod functional_area_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "SA")]
        SA,
        #[serde(rename = "WPN")]
        WPN,
        #[serde(rename = "DEF")]
        DEF,
        #[serde(rename = "SYS")]
        SYS,
        #[serde(rename = "DRV")]
        DRV,
        #[serde(rename = "STR")]
        STR,
        #[serde(rename = "COM")]
        COM,
        #[serde(rename = "BMS")]
        BMS,
    }

}

pub mod view_focus_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "IGNORE_FOCUS")]
        IGNORE_FOCUS,
        #[serde(rename = "REMOVE_FOCUS")]
        REMOVE_FOCUS,
        #[serde(rename = "SET_FOCUS")]
        SET_FOCUS,
    }

}

pub mod view_always_on_top_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "IGNORE_ALWAYS_ON_TOP")]
        IGNORE_ALWAYS_ON_TOP,
        #[serde(rename = "REMOVE_ALWAYS_ON_TOP")]
        REMOVE_ALWAYS_ON_TOP,
        #[serde(rename = "SET_ALWAYS_ON_TOP")]
        SET_ALWAYS_ON_TOP,
    }

}

