// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type FusedChannelOptionalType = Option<FusedChannelType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageFusionSettingsType {
    #[serde(rename = "IsFuseChannelsSupported")]
    pub is_fuse_channels_supported: bool,
    #[serde(rename = "SupportedMethodList")]
    pub supported_method_list: crate::common::StringListType,
    #[serde(rename = "SupportedChannelList")]
    pub supported_channel_list: crate::common::StringListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FusedChannelType {
    #[serde(rename = "Method")]
    pub method: String,
    #[serde(rename = "PrimaryChannelName")]
    pub primary_channel_name: String,
    #[serde(rename = "SecondaryChannelName")]
    pub secondary_channel_name: String,
    #[serde(rename = "PrimaryChannelLevel")]
    pub primary_channel_level: crate::common::PercentOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageFusionStatusType {
    #[serde(rename = "FusedChannel")]
    pub fused_channel: FusedChannelOptionalType,
    #[serde(rename = "IsAuto")]
    pub is_auto: bool,
}

