// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type InterpolationOptionalType = Option<interpolation_kind::Type>;

pub type FlipDirectionOptionalType = Option<flip_direction_kind::Type>;

pub type FrameDropListType = Vec<frame_drop_kind::Type>;

pub type FrameDropOptionalType = Option<FrameDropType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FrameDropType {
    #[serde(rename = "Mode")]
    pub mode: frame_drop_kind::Type,
    #[serde(rename = "EveryNthFrameToPass")]
    pub every_nth_frame_to_pass: crate::common::LongOptionalType,
    #[serde(rename = "EveryNthFrameToDrop")]
    pub every_nth_frame_to_drop: crate::common::LongOptionalType,
    #[serde(rename = "RandomFrameDropPercentage")]
    pub random_frame_drop_percentage: crate::common::PercentOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageInfoType {
    #[serde(rename = "Region")]
    pub region: crate::common::ImageRegionType,
    #[serde(rename = "RotationAngle")]
    pub rotation_angle: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "FlipDirection")]
    pub flip_direction: FlipDirectionOptionalType,
    #[serde(rename = "Interpolation")]
    pub interpolation: InterpolationOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageProcessingSettingsType {
    #[serde(rename = "SupportedFrameDropModes")]
    pub supported_frame_drop_modes: FrameDropListType,
    #[serde(rename = "IsCmdSetRegionSupported")]
    pub is_cmd_set_region_supported: bool,
    #[serde(rename = "IsCmdScaleSupported")]
    pub is_cmd_scale_supported: bool,
    #[serde(rename = "IsCmdRotateSupported")]
    pub is_cmd_rotate_supported: bool,
    #[serde(rename = "IsCmdFlipSupported")]
    pub is_cmd_flip_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageProcessingStatusType {
    #[serde(rename = "InputImageSize")]
    pub input_image_size: crate::common::PixelRectSizeType,
    #[serde(rename = "OutputImageInfo")]
    pub output_image_info: ImageInfoType,
    #[serde(rename = "FrameDropMethod")]
    pub frame_drop_method: FrameDropOptionalType,
}

pub mod interpolation_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Nearest_Neighbour")]
        Nearest_Neighbour,
        #[serde(rename = "Bilinear")]
        Bilinear,
        #[serde(rename = "Bicubic")]
        Bicubic,
        #[serde(rename = "Spline")]
        Spline,
        #[serde(rename = "Lanczos")]
        Lanczos,
        #[serde(rename = "Wavelet")]
        Wavelet,
    }

}

pub mod flip_direction_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Horizontal")]
        Horizontal,
        #[serde(rename = "Vertical")]
        Vertical,
        #[serde(rename = "Horizontal_Vertical")]
        Horizontal_Vertical,
    }

}

pub mod frame_drop_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "PassEveryNthFrame")]
        PassEveryNthFrame,
        #[serde(rename = "DropEveryNthFrame")]
        DropEveryNthFrame,
        #[serde(rename = "DropRandomPercentage")]
        DropRandomPercentage,
    }

}

