// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ViewportListType = Vec<ViewportType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ViewportType {
    #[serde(rename = "SourceChannel")]
    pub source_channel: String,
    #[serde(rename = "SourceRectangle")]
    pub source_rectangle: crate::common::PixelRegionType,
    #[serde(rename = "TargetRectangle")]
    pub target_rectangle: crate::common::PixelRegionType,
    #[serde(rename = "TargetZLevel")]
    pub target_z_level: u32,
    #[serde(rename = "TargetAlpha")]
    pub target_alpha: crate::common::ProportionalOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageComposerSettingsType {
    #[serde(rename = "IsConfigViewportsSupported")]
    pub is_config_viewports_supported: bool,
    #[serde(rename = "CanvasSize")]
    pub canvas_size: crate::common::PixelRectSizeType,
    #[serde(rename = "CanvasBackgroundRgbaColorCode")]
    pub canvas_background_rgba_color_code: u32,
    #[serde(rename = "AvailableSourceChannels")]
    pub available_source_channels: crate::common::StringListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ImageComposerChannelStatusType {
    #[serde(rename = "Size")]
    pub size: crate::common::PixelRectSizeType,
}

