// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ControlModeOptionalType = Option<control_mode_kind::Type>;

pub type AxisRotationConstraintsOptionalType = Option<AxisRotationConstraintsType>;

pub type AxisRotationConstraintsListType = Vec<AxisRotationConstraintsType>;

pub type AxisControlOptionalType = Option<AxisControlType>;

pub type AxisRotationListType = Vec<AxisRotationType>;

pub type StoredAxisRotationListType = Vec<StoredAxisRotationType>;

pub type AxisListType = Vec<AxisType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisRotationConstraintsType {
    #[serde(rename = "AxisId")]
    pub axis_id: String,
    #[serde(rename = "MinAngle")]
    pub min_angle: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "MaxAngle")]
    pub max_angle: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "MaxAngularSpeed")]
    pub max_angular_speed: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "MaxAngularAcceleration")]
    pub max_angular_acceleration: crate::common::AngularAccelerationDegreesPerSecPerSecOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisControlType {
    #[serde(rename = "Mode")]
    pub mode: ControlModeOptionalType,
    #[serde(rename = "TimeToPosition")]
    pub time_to_position: crate::common::TimeSecondsOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisRotationType {
    #[serde(rename = "AxisId")]
    pub axis_id: String,
    #[serde(rename = "Angle")]
    pub angle: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "AngleIncrement")]
    pub angle_increment: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "AbsoluteSpeed")]
    pub absolute_speed: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "RelativeSpeed")]
    pub relative_speed: crate::common::PercentOptionalType,
    #[serde(rename = "AxisControl")]
    pub axis_control: AxisControlOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct StoredAxisRotationType {
    #[serde(rename = "AxisId")]
    pub axis_id: String,
    #[serde(rename = "DatasetId")]
    pub dataset_id: String,
    #[serde(rename = "AxisRotation")]
    pub axis_rotation: AxisRotationType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AxisType {
    #[serde(rename = "AxisId")]
    pub axis_id: String,
    #[serde(rename = "AxisPosition")]
    pub axis_position: crate::common::PositionOptionalType,
    #[serde(rename = "NormalisedAxisDirection")]
    pub normalised_axis_direction: crate::common::AxisDirectionOptionalType,
    #[serde(rename = "AxisRotationConstraints")]
    pub axis_rotation_constraints: AxisRotationConstraintsOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct KinematicChainSettingsType {
    #[serde(rename = "Axes")]
    pub axes: AxisListType,
    #[serde(rename = "IsConfigAxisRotationConstraintsSupported")]
    pub is_config_axis_rotation_constraints_supported: bool,
    #[serde(rename = "IsNotifyAxisRotationSupported")]
    pub is_notify_axis_rotation_supported: bool,
    #[serde(rename = "IsReportAxisRotationSupported")]
    pub is_report_axis_rotation_supported: bool,
    #[serde(rename = "AreStoredAxisRotationsSupported")]
    pub are_stored_axis_rotations_supported: bool,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct KinematicChainStatusType {
    #[serde(rename = "StoredAxisRotationList")]
    pub stored_axis_rotation_list: StoredAxisRotationListType,
}

pub mod control_mode_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Locked")]
        Locked,
        #[serde(rename = "Unstabilised")]
        Unstabilised,
        #[serde(rename = "Stabilised")]
        Stabilised,
    }

}

