// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type LanguageType = String;

pub type LanguageListType = Vec<LanguageType>;

pub type TextListType = Vec<TextType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TextType {
    #[serde(rename = "Language")]
    pub language: LanguageType,
    #[serde(rename = "Text")]
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LanguageManagerSettingsType {
    #[serde(rename = "DefaultLanguage")]
    pub default_language: LanguageType,
    #[serde(rename = "SupportedLanguages")]
    pub supported_languages: LanguageListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LanguageManagerStatusType {
    #[serde(rename = "SelectedLanguage")]
    pub selected_language: LanguageType,
}

