// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type MeasurementStrengthOptionalType = Option<measurement_strength::Type>;

pub type RangeMeasurementListType = Vec<RangeMeasurementType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RangeMeasurementType {
    #[serde(rename = "Range")]
    pub range: crate::common::DistanceMetersType,
    #[serde(rename = "Strength")]
    pub strength: MeasurementStrengthOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LrfSettingsType {
    #[serde(rename = "MinimumRange")]
    pub minimum_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "MaximumRange")]
    pub maximum_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "IsSetFirstOrLastMeasurementSupported")]
    pub is_set_first_or_last_measurement_supported: bool,
    #[serde(rename = "IsSetUserRangeSupported")]
    pub is_set_user_range_supported: bool,
    #[serde(rename = "IsInhibitLaserFiringSupported")]
    pub is_inhibit_laser_firing_supported: bool,
    #[serde(rename = "IsMultiFireLaserSupported")]
    pub is_multi_fire_laser_supported: bool,
    #[serde(rename = "IsSingleFireLaserSupported")]
    pub is_single_fire_laser_supported: bool,
    #[serde(rename = "IsMultiPulseSupported")]
    pub is_multi_pulse_supported: bool,
    #[serde(rename = "IsUserMinimumRangeSupported")]
    pub is_user_minimum_range_supported: bool,
    #[serde(rename = "IsUserMaximumRangeSupported")]
    pub is_user_maximum_range_supported: bool,
    #[serde(rename = "RangeUncertainty")]
    pub range_uncertainty: crate::common::UncertaintyType,
    #[serde(rename = "MaximumDetectionsPerMeasurement")]
    pub maximum_detections_per_measurement: u32,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LrfStatusType {
    #[serde(rename = "State")]
    pub state: lrf_state::Type,
    #[serde(rename = "UserDefinedMinimumRange")]
    pub user_defined_minimum_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "UserDefinedMaximumRange")]
    pub user_defined_maximum_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "StrongestMeasurement")]
    pub strongest_measurement: first_or_last::Type,
    #[serde(rename = "MultiFireFrequency")]
    pub multi_fire_frequency: crate::common::FrequencyHertzOptionalType,
    #[serde(rename = "LaserFireCountTotal")]
    pub laser_fire_count_total: crate::common::ULongLongOptionalType,
    #[serde(rename = "FiringInhibitingComponentIds")]
    pub firing_inhibiting_component_ids: crate::common::StringListType,
}

pub mod lrf_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "Firing_Inhibited")]
        Firing_Inhibited,
        #[serde(rename = "Firing_Enabled")]
        Firing_Enabled,
        #[serde(rename = "Firing_Multi_Pulse_Mode")]
        Firing_Multi_Pulse_Mode,
        #[serde(rename = "Firing_Single_Pulse_Mode")]
        Firing_Single_Pulse_Mode,
        #[serde(rename = "Firing_Inhibited_Multi_Pulse_Mode")]
        Firing_Inhibited_Multi_Pulse_Mode,
    }

}

pub mod first_or_last {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "First")]
        First,
        #[serde(rename = "Last")]
        Last,
    }

}

pub mod measurement_strength {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Strong")]
        Strong,
        #[serde(rename = "Weak")]
        Weak,
    }

}

