// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type LogMessageListType = Vec<LogMessageType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LogMessageType {
    #[serde(rename = "Level")]
    pub level: log_level_kind::Type,
    #[serde(rename = "Message")]
    pub message: String,
    #[serde(rename = "UnixTimestamp")]
    pub unix_timestamp: crate::common::UnixTimeType,
    #[serde(rename = "FunctionName")]
    pub function_name: crate::common::StringOptionalType,
    #[serde(rename = "FileName")]
    pub file_name: crate::common::StringOptionalType,
    #[serde(rename = "LoggerName")]
    pub logger_name: crate::common::StringOptionalType,
    #[serde(rename = "ComponentName")]
    pub component_name: crate::common::StringOptionalType,
    #[serde(rename = "Line")]
    pub line: crate::common::ULongOptionalType,
    #[serde(rename = "Id")]
    pub id: crate::common::ULongLongOptionalType,
    #[serde(rename = "ProcessId")]
    pub process_id: crate::common::ULongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LogSettingsType {
    #[serde(rename = "Level")]
    pub level: log_level_kind::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LogMessageRequestType {
    #[serde(rename = "AfterId")]
    pub after_id: crate::common::ULongOptionalType,
    #[serde(rename = "AfterUnixTimestamp")]
    pub after_unix_timestamp: crate::common::UnixTimeOptionalType,
}

pub mod log_level_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Off")]
        Off,
        #[serde(rename = "Critical")]
        Critical,
        #[serde(rename = "Error")]
        Error,
        #[serde(rename = "Warn")]
        Warn,
        #[serde(rename = "Info")]
        Info,
        #[serde(rename = "Debug")]
        Debug,
        #[serde(rename = "Trace")]
        Trace,
    }

}

