// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type InertiaTensorOptionalType = Option<InertiaTensorType>;

pub type LinkListType = Vec<LinkType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InertiaTensorType {
    #[serde(rename = "XX")]
    pub xx: crate::common::MomentOfInertiaKilogramMetresSquaredType,
    #[serde(rename = "YY")]
    pub yy: crate::common::MomentOfInertiaKilogramMetresSquaredType,
    #[serde(rename = "ZZ")]
    pub zz: crate::common::MomentOfInertiaKilogramMetresSquaredType,
    #[serde(rename = "XY")]
    pub xy: crate::common::MomentOfInertiaKilogramMetresSquaredType,
    #[serde(rename = "YZ")]
    pub yz: crate::common::MomentOfInertiaKilogramMetresSquaredType,
    #[serde(rename = "XZ")]
    pub xz: crate::common::MomentOfInertiaKilogramMetresSquaredType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct InertiaType {
    #[serde(rename = "GravityCentre")]
    pub gravity_centre: crate::common::PositionOptionalType,
    #[serde(rename = "Mass")]
    pub mass: crate::common::MassKilogramsOptionalType,
    #[serde(rename = "InertiaTensor")]
    pub inertia_tensor: InertiaTensorOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LinkType {
    #[serde(rename = "LinkId")]
    pub link_id: String,
    #[serde(rename = "AxisId")]
    pub axis_id: String,
    #[serde(rename = "ActuatorId")]
    pub actuator_id: String,
    #[serde(rename = "Inertia")]
    pub inertia: InertiaType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ManipulatorSettingsType {
    #[serde(rename = "Links")]
    pub links: LinkListType,
    #[serde(rename = "SupportedOperationStatusList")]
    pub supported_operation_status_list: crate::common::OperationStatusListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ManipulatorStatusType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LinkStatusType {
    #[serde(rename = "Inertia")]
    pub inertia: InertiaType,
}

