// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AtmosphericType {
    #[serde(rename = "Temperature")]
    pub temperature: crate::common::TemperatureKelvinsSelectionOptionalType,
    #[serde(rename = "Pressure")]
    pub pressure: crate::common::PressurePascalsSelectionOptionalType,
    #[serde(rename = "RelativeHumidity")]
    pub relative_humidity: crate::common::PercentSelectionOptionalType,
    #[serde(rename = "WindVelocity")]
    pub wind_velocity: crate::common::LinearVelocitySelectionOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MetSensorSettingsType {
    #[serde(rename = "IsTemperatureSupported")]
    pub is_temperature_supported: bool,
    #[serde(rename = "MinTemperature")]
    pub min_temperature: crate::common::TemperatureKelvinsOptionalType,
    #[serde(rename = "MaxTemperature")]
    pub max_temperature: crate::common::TemperatureKelvinsOptionalType,
    #[serde(rename = "IsPressureSupported")]
    pub is_pressure_supported: bool,
    #[serde(rename = "MinPressure")]
    pub min_pressure: crate::common::PressurePascalsOptionalType,
    #[serde(rename = "MaxPressure")]
    pub max_pressure: crate::common::PressurePascalsOptionalType,
    #[serde(rename = "IsWindVelocitySupported")]
    pub is_wind_velocity_supported: bool,
    #[serde(rename = "MaxWindSpeed")]
    pub max_wind_speed: crate::common::SpeedMetersPerSecOptionalType,
    #[serde(rename = "IsRelativeHumiditySupported")]
    pub is_relative_humidity_supported: bool,
    #[serde(rename = "MaxRelativeHumidity")]
    pub max_relative_humidity: crate::common::PercentOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

