// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type TaskCategoryOptionalType = Option<task_category_kind::Type>;

pub type TaskOptionalType = Option<TaskType>;

pub type TaskListType = Vec<TaskType>;

pub type WaypointOptionalType = Option<WaypointType>;

pub type CommandedActionListType = Vec<CommandedActionType>;

pub type ActionListType = Vec<ActionType>;

pub type MissionOptionalType = Option<MissionType>;

pub type SurfacePatchListType = Vec<SurfacePatchType>;

pub type CellListType = Vec<CellType>;

pub type CellMatrixType = Vec<CellListType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TaskType {
    #[serde(rename = "EnumeratedValue")]
    pub enumerated_value: TaskCategoryOptionalType,
    #[serde(rename = "IntegerValue")]
    pub integer_value: crate::common::ULongOptionalType,
    #[serde(rename = "TextualValue")]
    pub textual_value: crate::common::StringOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct WaypointType {
    #[serde(rename = "Position")]
    pub position: crate::common::PositionType,
    #[serde(rename = "Attitude")]
    pub attitude: crate::common::AttitudeOptionalType,
    #[serde(rename = "LinearVelocity")]
    pub linear_velocity: crate::common::LinearVelocityOptionalType,
    #[serde(rename = "AbsoluteArrivalTime")]
    pub absolute_arrival_time: crate::common::UtcOptionalType,
    #[serde(rename = "TimeUntilArrival")]
    pub time_until_arrival: crate::common::TimeSecondsOptionalType,
    #[serde(rename = "DepartureTime")]
    pub departure_time: crate::common::UtcOptionalType,
    #[serde(rename = "ResidenceTime")]
    pub residence_time: crate::common::TimeSecondsOptionalType,
    #[serde(rename = "PositionOfInterest")]
    pub position_of_interest: crate::common::PositionOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CommandedActionType {
    #[serde(rename = "Task")]
    pub task: TaskType,
    #[serde(rename = "Waypoint")]
    pub waypoint: WaypointOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActionType {
    #[serde(rename = "CurrentTask")]
    pub current_task: TaskType,
    #[serde(rename = "NextTask")]
    pub next_task: TaskOptionalType,
    #[serde(rename = "CurrentWaypoint")]
    pub current_waypoint: WaypointOptionalType,
    #[serde(rename = "NextWaypoint")]
    pub next_waypoint: WaypointOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MissionType {
    #[serde(rename = "Actions")]
    pub actions: CommandedActionListType,
    #[serde(rename = "Revision")]
    pub revision: u32,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SurfacePatchType {
    #[serde(rename = "Id")]
    pub id: u32,
    #[serde(rename = "Height")]
    pub height: crate::common::DistanceMetersType,
    #[serde(rename = "HeightVariance")]
    pub height_variance: f64,
    #[serde(rename = "Depth")]
    pub depth: crate::common::DistanceMetersType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CellType {
    #[serde(rename = "RowId")]
    pub row_id: u32,
    #[serde(rename = "ColumnId")]
    pub column_id: u32,
    #[serde(rename = "SurfacePatchList")]
    pub surface_patch_list: SurfacePatchListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MultiLevelSurfaceMapType {
    #[serde(rename = "PartitionName")]
    pub partition_name: String,
    #[serde(rename = "CellWidth")]
    pub cell_width: crate::common::DistanceMetersType,
    #[serde(rename = "CellMatrix")]
    pub cell_matrix: CellMatrixType,
    #[serde(rename = "ReferencePosition")]
    pub reference_position: crate::common::PositionOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MissionCtrlSettingsType {
    #[serde(rename = "AreMissionsSupported")]
    pub are_missions_supported: bool,
    #[serde(rename = "AllowedMissionTasks")]
    pub allowed_mission_tasks: TaskListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MissionStatusType {
    #[serde(rename = "CurrentMissionName")]
    pub current_mission_name: String,
    #[serde(rename = "CurrentAction")]
    pub current_action: ActionType,
    #[serde(rename = "CurrentlyAllowedTasks")]
    pub currently_allowed_tasks: TaskListType,
    #[serde(rename = "Revision")]
    pub revision: u32,
}

pub mod task_category_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Connect")]
        Connect,
        #[serde(rename = "Disconnect")]
        Disconnect,
        #[serde(rename = "Arm")]
        Arm,
        #[serde(rename = "Disarm")]
        Disarm,
        #[serde(rename = "Fire")]
        Fire,
        #[serde(rename = "Observe")]
        Observe,
        #[serde(rename = "Climb")]
        Climb,
        #[serde(rename = "Descend")]
        Descend,
        #[serde(rename = "Takeoff")]
        Takeoff,
        #[serde(rename = "Land")]
        Land,
        #[serde(rename = "Reboot")]
        Reboot,
        #[serde(rename = "Shutdown")]
        Shutdown,
        #[serde(rename = "Loiter")]
        Loiter,
        #[serde(rename = "Return")]
        Return,
        #[serde(rename = "Follow")]
        Follow,
        #[serde(rename = "Stop")]
        Stop,
        #[serde(rename = "Resume")]
        Resume,
    }

}

