// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type StabStateOptionalType = Option<stab_state::Type>;

pub type ControlStateOptionalType = Option<control_state::Type>;

pub type MovementStateOptionalType = Option<movement_state::Type>;

pub type DriftCompensationKindOptionalType = Option<drift_compensation_kind::Type>;

pub type ScaledRateOptionalType = Option<ScaledRateType>;

pub type TgtAssignmentSearchPatternOptionalType = Option<TgtAssignmentSearchPatternType>;

pub type StoredPositionListType = Vec<StoredPositionType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MountAngleParamsType {
    #[serde(rename = "RelativeTo")]
    pub relative_to: relative_to_coord_system::Type,
    #[serde(rename = "HorizontalDirection")]
    pub horizontal_direction: crate::common::HorizontalDirectionOptionalType,
    #[serde(rename = "VerticalDirection")]
    pub vertical_direction: crate::common::VerticalDirectionOptionalType,
    #[serde(rename = "TimeToPosition")]
    pub time_to_position: crate::common::TimeSecondsOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScaledRateType {
    #[serde(rename = "AzimuthScaledRate")]
    pub azimuth_scaled_rate: f64,
    #[serde(rename = "ElevationScaledRate")]
    pub elevation_scaled_rate: f64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TgtAssignmentSearchPatternType {
    #[serde(rename = "TopLeft")]
    pub top_left: crate::common::SphericalPositionType,
    #[serde(rename = "BottomRight")]
    pub bottom_right: crate::common::SphericalPositionType,
    #[serde(rename = "StartPosition")]
    pub start_position: crate::common::SphericalPositionType,
    #[serde(rename = "StartDirectionHorizontal")]
    pub start_direction_horizontal: crate::common::horizontal_direction::Type,
    #[serde(rename = "StartDirectionVertical")]
    pub start_direction_vertical: crate::common::vertical_direction::Type,
    #[serde(rename = "Pattern")]
    pub pattern: search_pattern_kind::Type,
    #[serde(rename = "SearchReferenceHorizontal")]
    pub search_reference_horizontal: relative_to_coord_system::Type,
    #[serde(rename = "SearchReferenceVertical")]
    pub search_reference_vertical: relative_to_coord_system::Type,
    #[serde(rename = "SearchSpeed")]
    pub search_speed: crate::common::SphericalPositionRateType,
    #[serde(rename = "StepSize")]
    pub step_size: crate::common::AngleDegreesType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModeAvailabilityType {
    #[serde(rename = "GeneralControlModeAvailability")]
    pub general_control_mode_availability: crate::common::availability::Type,
    #[serde(rename = "StateMotorOffAvailability")]
    pub state_motor_off_availability: crate::common::availability::Type,
    #[serde(rename = "StateLockedAvailability")]
    pub state_locked_availability: crate::common::availability::Type,
    #[serde(rename = "StateStabAvailability")]
    pub state_stab_availability: crate::common::availability::Type,
    #[serde(rename = "StateUnstabAvailability")]
    pub state_unstab_availability: crate::common::availability::Type,
    #[serde(rename = "StateHorizontalStabAvailability")]
    pub state_horizontal_stab_availability: crate::common::availability::Type,
    #[serde(rename = "StateVerticalStabAvailability")]
    pub state_vertical_stab_availability: crate::common::availability::Type,
    #[serde(rename = "StateTargetAssignmentAvailability")]
    pub state_target_assignment_availability: crate::common::availability::Type,
    #[serde(rename = "StateSlavedToLeadingDeviceAvailability")]
    pub state_slaved_to_leading_device_availability: crate::common::availability::Type,
    #[serde(rename = "StateWideAreaScanAvailability")]
    pub state_wide_area_scan_availability: crate::common::availability::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModeSupportedType {
    #[serde(rename = "IsMotorOffSupported")]
    pub is_motor_off_supported: bool,
    #[serde(rename = "IsLockedSupported")]
    pub is_locked_supported: bool,
    #[serde(rename = "IsUnstabSupported")]
    pub is_unstab_supported: bool,
    #[serde(rename = "IsStabSupported")]
    pub is_stab_supported: bool,
    #[serde(rename = "IsHorizontalStabSupported")]
    pub is_horizontal_stab_supported: bool,
    #[serde(rename = "IsVerticalStabSupported")]
    pub is_vertical_stab_supported: bool,
    #[serde(rename = "IsTargetAssignmentSupported")]
    pub is_target_assignment_supported: bool,
    #[serde(rename = "IsSlavedToLeadingDeviceSupported")]
    pub is_slaved_to_leading_device_supported: bool,
    #[serde(rename = "IsWideAreaScanSupported")]
    pub is_wide_area_scan_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SearchActionSupportedType {
    #[serde(rename = "IsManualSearchSupported")]
    pub is_manual_search_supported: bool,
    #[serde(rename = "IsAutomatichSearchSupported")]
    pub is_automatich_search_supported: bool,
    #[serde(rename = "IsResetSearchSupported")]
    pub is_reset_search_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RelativeToCoordSystemSupportedType {
    #[serde(rename = "IsCurrentPositionSupported")]
    pub is_current_position_supported: bool,
    #[serde(rename = "IsVehicleSupported")]
    pub is_vehicle_supported: bool,
    #[serde(rename = "IsGeographicSupported")]
    pub is_geographic_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AngularLimitType {
    #[serde(rename = "MinimumAzimuth")]
    pub minimum_azimuth: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "MaximumAzimuth")]
    pub maximum_azimuth: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "MinimumElevation")]
    pub minimum_elevation: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "MaximumElevation")]
    pub maximum_elevation: crate::common::AngleDegreesOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct StoredPositionType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "Azimuth")]
    pub azimuth: crate::common::AngleDegreesType,
    #[serde(rename = "Elevation")]
    pub elevation: crate::common::AngleDegreesType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MountSettingsType {
    #[serde(rename = "SupportedModes")]
    pub supported_modes: ModeSupportedType,
    #[serde(rename = "IsCmdModeSupported")]
    pub is_cmd_mode_supported: bool,
    #[serde(rename = "IsConfigInputSourceSupported")]
    pub is_config_input_source_supported: bool,
    #[serde(rename = "IsConfigTgtAssignmentInputSourceSupported")]
    pub is_config_tgt_assignment_input_source_supported: bool,
    #[serde(rename = "IsConfigTgtAssignmentSearchInputSourceSupported")]
    pub is_config_tgt_assignment_search_input_source_supported: bool,
    #[serde(rename = "IsConfigTgtAssignmentSearchPatternSupported")]
    pub is_config_tgt_assignment_search_pattern_supported: bool,
    #[serde(rename = "IsConfigSlewLimitsSupported")]
    pub is_config_slew_limits_supported: bool,
    #[serde(rename = "IsConfigStorePositionSupported")]
    pub is_config_store_position_supported: bool,
    #[serde(rename = "IsCmdMoveToStoredPositionSupported")]
    pub is_cmd_move_to_stored_position_supported: bool,
    #[serde(rename = "IsNotifyAngleSupported")]
    pub is_notify_angle_supported: bool,
    #[serde(rename = "IsNotifyTgtAssignmentCartSupported")]
    pub is_notify_tgt_assignment_cart_supported: bool,
    #[serde(rename = "IsNotifyTgtAssignmentSphereSupported")]
    pub is_notify_tgt_assignment_sphere_supported: bool,
    #[serde(rename = "SupportedRelativeTo")]
    pub supported_relative_to: RelativeToCoordSystemSupportedType,
    #[serde(rename = "IsParamVerticalDirectionSupported")]
    pub is_param_vertical_direction_supported: bool,
    #[serde(rename = "IsParamHorizontalDirectionSupported")]
    pub is_param_horizontal_direction_supported: bool,
    #[serde(rename = "IsParamTimeToPositionSupported")]
    pub is_param_time_to_position_supported: bool,
    #[serde(rename = "IsCmdTgtAssignmentSearchActionSupported")]
    pub is_cmd_tgt_assignment_search_action_supported: bool,
    #[serde(rename = "SupportedSearchActions")]
    pub supported_search_actions: SearchActionSupportedType,
    #[serde(rename = "IsCmdAutoDriftCompensationSupported")]
    pub is_cmd_auto_drift_compensation_supported: bool,
    #[serde(rename = "IsCmdManualDriftCompensationSupported")]
    pub is_cmd_manual_drift_compensation_supported: bool,
    #[serde(rename = "IsCmdAllowExternalDriftCompensationSupported")]
    pub is_cmd_allow_external_drift_compensation_supported: bool,
    #[serde(rename = "IsCmdHorizontalAimingSupported")]
    pub is_cmd_horizontal_aiming_supported: bool,
    #[serde(rename = "IsSetOperationalModeRateAidSupported")]
    pub is_set_operational_mode_rate_aid_supported: bool,
    #[serde(rename = "IsConfigMaximumRateSupported")]
    pub is_config_maximum_rate_supported: bool,
    #[serde(rename = "IsNotifyRateAbsoluteSupported")]
    pub is_notify_rate_absolute_supported: bool,
    #[serde(rename = "IsNotifyRateScaledSupported")]
    pub is_notify_rate_scaled_supported: bool,
    #[serde(rename = "IsConfigLeadingDeviceSupported")]
    pub is_config_leading_device_supported: bool,
    #[serde(rename = "IsConfigSlavedDeviceSupported")]
    pub is_config_slaved_device_supported: bool,
    #[serde(rename = "HardLimits")]
    pub hard_limits: AngularLimitType,
    #[serde(rename = "OperatingStartTime")]
    pub operating_start_time: crate::common::TimeOptionalType,
    #[serde(rename = "EquipmentPosition")]
    pub equipment_position: crate::common::CoordinateTransformationType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MountStatusType {
    #[serde(rename = "InputSourceClientId")]
    pub input_source_client_id: String,
    #[serde(rename = "TgtAssignmentInputSourceClientId")]
    pub tgt_assignment_input_source_client_id: String,
    #[serde(rename = "TgtAssignmentSearchInputSourceClientId")]
    pub tgt_assignment_search_input_source_client_id: String,
    #[serde(rename = "StabState")]
    pub stab_state: StabStateOptionalType,
    #[serde(rename = "CtrlState")]
    pub ctrl_state: ControlStateOptionalType,
    #[serde(rename = "MaximumAzimuthRate")]
    pub maximum_azimuth_rate: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "MaximumElevationRate")]
    pub maximum_elevation_rate: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "DriftCompensationMode")]
    pub drift_compensation_mode: DriftCompensationKindOptionalType,
    #[serde(rename = "IsExternalDriftCompensationAllowed")]
    pub is_external_drift_compensation_allowed: bool,
    #[serde(rename = "DriftCompensationOffsetAzimuthRate")]
    pub drift_compensation_offset_azimuth_rate: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "DriftCompensationOffsetElevationRate")]
    pub drift_compensation_offset_elevation_rate: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "RateAidState")]
    pub rate_aid_state: crate::common::availability::Type,
    #[serde(rename = "IsModeRateAidActive")]
    pub is_mode_rate_aid_active: bool,
    #[serde(rename = "PositionState")]
    pub position_state: MovementStateOptionalType,
    #[serde(rename = "NumberOfSearchCycles")]
    pub number_of_search_cycles: crate::common::UShortOptionalType,
    #[serde(rename = "TgtAssignmentSearchState")]
    pub tgt_assignment_search_state: tgt_assignment_search_state_kind::Type,
    #[serde(rename = "TgtAssignmentSearchPattern")]
    pub tgt_assignment_search_pattern: TgtAssignmentSearchPatternOptionalType,
    #[serde(rename = "LeadingDeviceId")]
    pub leading_device_id: crate::common::LongOptionalType,
    #[serde(rename = "SlavedDeviceId")]
    pub slaved_device_id: crate::common::LongOptionalType,
    #[serde(rename = "OperationStageName")]
    pub operation_stage_name: String,
    #[serde(rename = "OverTemperature")]
    pub over_temperature: crate::common::OperationFaultType,
    #[serde(rename = "SlewLimits")]
    pub slew_limits: AngularLimitType,
    #[serde(rename = "ModeAvailability")]
    pub mode_availability: ModeAvailabilityType,
    #[serde(rename = "HorizontalAimingState")]
    pub horizontal_aiming_state: crate::common::availability::Type,
    #[serde(rename = "IsHorizontalAimingEnabled")]
    pub is_horizontal_aiming_enabled: bool,
    #[serde(rename = "StoredPositionList")]
    pub stored_position_list: StoredPositionListType,
    #[serde(rename = "AvailableInputSources")]
    pub available_input_sources: crate::common::StringListType,
    #[serde(rename = "AvailableTgtAssignmentInputSources")]
    pub available_tgt_assignment_input_sources: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MountPositionType {
    #[serde(rename = "Azimuth")]
    pub azimuth: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "Elevation")]
    pub elevation: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "AzimuthNorth")]
    pub azimuth_north: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "ElevationHorizon")]
    pub elevation_horizon: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "AzimuthRate")]
    pub azimuth_rate: crate::common::AngleRateDegreesPerSecOptionalType,
    #[serde(rename = "ElevationRate")]
    pub elevation_rate: crate::common::AngleRateDegreesPerSecOptionalType,
}

pub mod mode_command {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Motor_Off")]
        Motor_Off,
        #[serde(rename = "Locked")]
        Locked,
        #[serde(rename = "Select")]
        Select,
        #[serde(rename = "Deselect")]
        Deselect,
        #[serde(rename = "Unstab")]
        Unstab,
        #[serde(rename = "Stab")]
        Stab,
        #[serde(rename = "Horizontal_Stab")]
        Horizontal_Stab,
        #[serde(rename = "Vertical_Stab")]
        Vertical_Stab,
        #[serde(rename = "Target_Assignment")]
        Target_Assignment,
        #[serde(rename = "Slaved_To_Leading_Device")]
        Slaved_To_Leading_Device,
        #[serde(rename = "Wide_Area_Scan")]
        Wide_Area_Scan,
    }

}

pub mod stab_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Motor_Off")]
        Motor_Off,
        #[serde(rename = "Locked")]
        Locked,
        #[serde(rename = "Unstab")]
        Unstab,
        #[serde(rename = "Stab")]
        Stab,
        #[serde(rename = "Horizontal_Stab")]
        Horizontal_Stab,
        #[serde(rename = "Vertical_Stab")]
        Vertical_Stab,
        #[serde(rename = "Selecting")]
        Selecting,
        #[serde(rename = "Deselecting")]
        Deselecting,
        #[serde(rename = "Deselected")]
        Deselected,
    }

}

pub mod control_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Controlled_By_Rate")]
        Controlled_By_Rate,
        #[serde(rename = "Controlled_By_Angle")]
        Controlled_By_Angle,
        #[serde(rename = "Target_Assignment")]
        Target_Assignment,
        #[serde(rename = "Slaved_To_Leading_Device")]
        Slaved_To_Leading_Device,
        #[serde(rename = "Wide_Area_Scan")]
        Wide_Area_Scan,
        #[serde(rename = "Controlled_By_Video_Tracker")]
        Controlled_By_Video_Tracker,
        #[serde(rename = "Controlled_By_Video_Tracker_Coasting")]
        Controlled_By_Video_Tracker_Coasting,
    }

}

pub mod movement_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Position_Reached")]
        Position_Reached,
        #[serde(rename = "Position_Not_Reached")]
        Position_Not_Reached,
    }

}

pub mod drift_compensation_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "Auto")]
        Auto,
        #[serde(rename = "Allowed")]
        Allowed,
        #[serde(rename = "Not_Allowed")]
        Not_Allowed,
        #[serde(rename = "Cancelled")]
        Cancelled,
    }

}

pub mod relative_to_coord_system {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Zero_Position")]
        Zero_Position,
        #[serde(rename = "Current_Position")]
        Current_Position,
        #[serde(rename = "Vehicle")]
        Vehicle,
        #[serde(rename = "Geographic")]
        Geographic,
    }

}

pub mod tgt_assignment_search_cmd_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Automatic_Search")]
        Automatic_Search,
        #[serde(rename = "Manual_Search")]
        Manual_Search,
        #[serde(rename = "Reset_Search")]
        Reset_Search,
    }

}

pub mod tgt_assignment_search_state_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "No_Search")]
        No_Search,
        #[serde(rename = "Init")]
        Init,
        #[serde(rename = "Manual_Search")]
        Manual_Search,
        #[serde(rename = "Automatic_Search")]
        Automatic_Search,
    }

}

pub mod search_pattern_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Azimuth_Continuous_Elevation_Step")]
        Azimuth_Continuous_Elevation_Step,
        #[serde(rename = "Elevation_Continuous_Azimuth_Step")]
        Elevation_Continuous_Azimuth_Step,
        #[serde(rename = "Both_Continuous")]
        Both_Continuous,
        #[serde(rename = "Both_Step")]
        Both_Step,
    }

}

