// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type DriftCompensationOptionalType = Option<drift_compensation_kind::Type>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MountSettingsType {
    #[serde(rename = "SupportedOperationStatusList")]
    pub supported_operation_status_list: crate::common::OperationStatusListType,
    #[serde(rename = "IsCmdModeSupported")]
    pub is_cmd_mode_supported: bool,
    #[serde(rename = "IsConfigInputSourceSupported")]
    pub is_config_input_source_supported: bool,
    #[serde(rename = "IsConfigAssignmentInputSourceSupported")]
    pub is_config_assignment_input_source_supported: bool,
    #[serde(rename = "IsCmdAutoDriftCompensationSupported")]
    pub is_cmd_auto_drift_compensation_supported: bool,
    #[serde(rename = "IsCmdManualDriftCompensationSupported")]
    pub is_cmd_manual_drift_compensation_supported: bool,
    #[serde(rename = "IsCmdExternalDriftCompensationAllowedSupported")]
    pub is_cmd_external_drift_compensation_allowed_supported: bool,
    #[serde(rename = "OperatingStartTime")]
    pub operating_start_time: crate::common::TimeOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MountStatusType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
    #[serde(rename = "InputSourceClientId")]
    pub input_source_client_id: String,
    #[serde(rename = "AssignmentInputSourceClientId")]
    pub assignment_input_source_client_id: String,
    #[serde(rename = "DriftCompensationMode")]
    pub drift_compensation_mode: DriftCompensationOptionalType,
    #[serde(rename = "IsExternalDriftCompensationAllowed")]
    pub is_external_drift_compensation_allowed: bool,
    #[serde(rename = "DriftCompensationOffsetRate")]
    pub drift_compensation_offset_rate: crate::common::SphericalPositionRateOptionalType,
    #[serde(rename = "AvailableInputSources")]
    pub available_input_sources: crate::common::StringListType,
    #[serde(rename = "AvailableAssignmentInputSources")]
    pub available_assignment_input_sources: crate::common::StringListType,
    #[serde(rename = "IsClientIdFilterEnabled")]
    pub is_client_id_filter_enabled: bool,
}

pub mod drift_compensation_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "Auto")]
        Auto,
        #[serde(rename = "Allowed")]
        Allowed,
        #[serde(rename = "Not_Allowed")]
        Not_Allowed,
        #[serde(rename = "Cancelled")]
        Cancelled,
    }

}

