// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type OperatorAcknowledgeKindOptionalType = Option<operator_acknowledge_kind::Type>;

pub type AssignListType = Vec<AssignType>;

pub type FusionInfoOptionalType = Option<FusionInfoType>;

pub type SensorRawDetectionListType = Vec<SensorRawDetectionType>;

pub type ReportingUnitOptionalType = Option<ReportingUnitType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AssignType {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "UnitName")]
    pub unit_name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FusionInfoType {
    #[serde(rename = "AssociatedClusteredObjects")]
    pub associated_clustered_objects: crate::common::ObjectIdListType,
    #[serde(rename = "ComprisedRawObjects")]
    pub comprised_raw_objects: crate::common::ObjectIdListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct OwnInfoType {
    #[serde(rename = "Position")]
    pub position: crate::common::PositionType,
    #[serde(rename = "Attitude")]
    pub attitude: crate::common::AttitudeType,
    #[serde(rename = "LinearVelocity")]
    pub linear_velocity: crate::common::LinearVelocityOptionalType,
    #[serde(rename = "AngularVelocity")]
    pub angular_velocity: crate::common::AngularVelocityOptionalType,
    #[serde(rename = "UnitName")]
    pub unit_name: String,
    #[serde(rename = "UnitId")]
    pub unit_id: crate::common::ObjectIdOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SensorRawDetectionType {
    #[serde(rename = "DetectingSensorName")]
    pub detecting_sensor_name: String,
    #[serde(rename = "TypeOfDetectingSensor")]
    pub type_of_detecting_sensor: crate::common::SensorType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationListType,
    #[serde(rename = "ObjectPositionList")]
    pub object_position_list: crate::common::PositionListType,
    #[serde(rename = "ObjectVelocityList")]
    pub object_velocity_list: crate::common::LinearVelocityListType,
    #[serde(rename = "ObjectDimensions")]
    pub object_dimensions: crate::common::ObjectDimensionsOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ReportingUnitType {
    #[serde(rename = "Id")]
    pub id: crate::common::ObjectIdType,
    #[serde(rename = "Name")]
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PointObjectType {
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationOptionalType,
    #[serde(rename = "TypeOfReportingInstance")]
    pub type_of_reporting_instance: crate::common::SensorType,
    #[serde(rename = "ThreatLevel")]
    pub threat_level: crate::common::ThreatLevelType,
    #[serde(rename = "Label")]
    pub label: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "CreationTime")]
    pub creation_time: crate::common::TimeType,
    #[serde(rename = "LastUpdateTime")]
    pub last_update_time: crate::common::TimeType,
    #[serde(rename = "InvariantPositionCoordinateFrame")]
    pub invariant_position_coordinate_frame: String,
    #[serde(rename = "SourcePosition")]
    pub source_position: crate::common::PositionType,
    #[serde(rename = "PositionList")]
    pub position_list: crate::common::PositionListType,
    #[serde(rename = "SourceVelocity")]
    pub source_velocity: crate::common::LinearVelocityOptionalType,
    #[serde(rename = "VelocityList")]
    pub velocity_list: crate::common::LinearVelocityListType,
    #[serde(rename = "ObjectDimensions")]
    pub object_dimensions: crate::common::ObjectDimensionsOptionalType,
    #[serde(rename = "ObjectDimensionsExtension")]
    pub object_dimensions_extension: crate::common::ObjectDimensionsListType,
    #[serde(rename = "SensorDetectionList")]
    pub sensor_detection_list: SensorRawDetectionListType,
    #[serde(rename = "FusionInfo")]
    pub fusion_info: FusionInfoOptionalType,
    #[serde(rename = "AssignedTo")]
    pub assigned_to: AssignListType,
    #[serde(rename = "ReportingUnit")]
    pub reporting_unit: ReportingUnitOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
    #[serde(rename = "Snapshot")]
    pub snapshot: crate::common::ImageOptionalType,
    #[serde(rename = "OperatorAcknowledge")]
    pub operator_acknowledge: operator_acknowledge_kind::Type,
    #[serde(rename = "Relations")]
    pub relations: crate::common::ObjectRelationListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MultiPointObjectType {
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationOptionalType,
    #[serde(rename = "TypeOfReportingInstance")]
    pub type_of_reporting_instance: crate::common::SensorType,
    #[serde(rename = "ThreatLevel")]
    pub threat_level: crate::common::ThreatLevelType,
    #[serde(rename = "Label")]
    pub label: String,
    #[serde(rename = "Description")]
    pub description: String,
    #[serde(rename = "CreationTime")]
    pub creation_time: crate::common::TimeType,
    #[serde(rename = "LastUpdateTime")]
    pub last_update_time: crate::common::TimeType,
    #[serde(rename = "InvariantPositionCoordinateFrame")]
    pub invariant_position_coordinate_frame: String,
    #[serde(rename = "SourceMultiPosition")]
    pub source_multi_position: crate::common::MultiPositionType,
    #[serde(rename = "MultiPositionList")]
    pub multi_position_list: crate::common::MultiPositionListType,
    #[serde(rename = "IsClosed")]
    pub is_closed: bool,
    #[serde(rename = "AssignedTo")]
    pub assigned_to: AssignListType,
    #[serde(rename = "ReportingUnit")]
    pub reporting_unit: ReportingUnitOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
    #[serde(rename = "Snapshot")]
    pub snapshot: crate::common::ImageOptionalType,
    #[serde(rename = "OperatorAcknowledge")]
    pub operator_acknowledge: operator_acknowledge_kind::Type,
    #[serde(rename = "Relations")]
    pub relations: crate::common::ObjectRelationListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModifyObjectType {
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityOptionalType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationOptionalType,
    #[serde(rename = "ClearClassification")]
    pub clear_classification: bool,
    #[serde(rename = "TypeOfReportingInstance")]
    pub type_of_reporting_instance: crate::common::SensorOptionalType,
    #[serde(rename = "ThreatLevel")]
    pub threat_level: crate::common::ThreatLevelOptionalType,
    #[serde(rename = "Description")]
    pub description: crate::common::StringOptionalType,
    #[serde(rename = "InvariantPositionCoordinateFrame")]
    pub invariant_position_coordinate_frame: crate::common::StringOptionalType,
    #[serde(rename = "ReportingUnit")]
    pub reporting_unit: ReportingUnitOptionalType,
    #[serde(rename = "ClearReportingUnit")]
    pub clear_reporting_unit: bool,
    #[serde(rename = "AssignedTo")]
    pub assigned_to: AssignListType,
    #[serde(rename = "ClearAssignedTo")]
    pub clear_assigned_to: bool,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
    #[serde(rename = "Snapshot")]
    pub snapshot: crate::common::ImageOptionalType,
    #[serde(rename = "OperatorAcknowledge")]
    pub operator_acknowledge: OperatorAcknowledgeKindOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModifyPointType {
    #[serde(rename = "Data")]
    pub data: ModifyObjectType,
    #[serde(rename = "SourcePosition")]
    pub source_position: crate::common::PositionOptionalType,
    #[serde(rename = "SourceVelocity")]
    pub source_velocity: crate::common::LinearVelocityOptionalType,
    #[serde(rename = "ClearSourceVelocity")]
    pub clear_source_velocity: bool,
    #[serde(rename = "ObjectDimensions")]
    pub object_dimensions: crate::common::ObjectDimensionsOptionalType,
    #[serde(rename = "ClearObjectDimensions")]
    pub clear_object_dimensions: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModifyMultiPointType {
    #[serde(rename = "Data")]
    pub data: ModifyObjectType,
    #[serde(rename = "SourceMultiPosition")]
    pub source_multi_position: crate::common::MultiPositionOptionalType,
    #[serde(rename = "IsClosed")]
    pub is_closed: crate::common::BooleanOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ChangeEventTriggerType {
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationOptionalType,
    #[serde(rename = "ThreatLevel")]
    pub threat_level: crate::common::ThreatLevelType,
    #[serde(rename = "AssignedTo")]
    pub assigned_to: AssignListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ParameterDifferenceType {
    #[serde(rename = "OldData")]
    pub old_data: ChangeEventTriggerType,
    #[serde(rename = "NewData")]
    pub new_data: ChangeEventTriggerType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ObjectManagerSettingsType {
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

pub mod operator_acknowledge_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "NotAcknowledged")]
        NotAcknowledged,
        #[serde(rename = "Acknowledged")]
        Acknowledged,
        #[serde(rename = "Acknowledged_IsNotOfInterest")]
        Acknowledged_IsNotOfInterest,
        #[serde(rename = "Acknowledged_IsOfInterest")]
        Acknowledged_IsOfInterest,
        #[serde(rename = "Escalate")]
        Escalate,
    }

}

