// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct OverlayCtrlSettingsType {
    #[serde(rename = "IsEnableOverlaySupported")]
    pub is_enable_overlay_supported: bool,
    #[serde(rename = "SupportedOverlaysList")]
    pub supported_overlays_list: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct OverlayCtrlStatusType {
    #[serde(rename = "IsEnabled")]
    pub is_enabled: bool,
    #[serde(rename = "ColourStyle")]
    pub colour_style: crate::common::ColourStyleOptionalType,
}

