// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type VideoChannelListType = Vec<VideoChannelType>;

pub type VideoCutoutInfoListType = Vec<VideoCutoutInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VideoChannelType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "EncryptionInfo")]
    pub encryption_info: crate::common::EncryptionOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RecordingSettingsType {
    #[serde(rename = "IsStartStopRecordingSupported")]
    pub is_start_stop_recording_supported: bool,
    #[serde(rename = "IsCaptureVideoCutoutSupported")]
    pub is_capture_video_cutout_supported: bool,
    #[serde(rename = "SupportedRecordingChannels")]
    pub supported_recording_channels: VideoChannelListType,
    #[serde(rename = "IsCaptureImageSupported")]
    pub is_capture_image_supported: bool,
    #[serde(rename = "SupportedImageCaptureChannels")]
    pub supported_image_capture_channels: VideoChannelListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VideoCutoutInfoType {
    #[serde(rename = "VideoChannelId")]
    pub video_channel_id: String,
    #[serde(rename = "StartTime")]
    pub start_time: crate::common::TimeType,
    #[serde(rename = "StopTime")]
    pub stop_time: crate::common::TimeType,
    #[serde(rename = "Description")]
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RecordingStatusType {
    #[serde(rename = "VideoCutoutList")]
    pub video_cutout_list: VideoCutoutInfoListType,
    #[serde(rename = "InProgressRecordingsList")]
    pub in_progress_recordings_list: crate::common::StringListType,
    #[serde(rename = "NumberOfCapturedImages")]
    pub number_of_captured_images: crate::common::ULongOptionalType,
}

