// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type SupportedReplayChannelsListType = Vec<SupportedReplayChannelsType>;

pub type ReplayTimelineListType = Vec<ReplayTimelineType>;

pub type ReplayChannelInfoListType = Vec<ReplayChannelInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SupportedReplayChannelsType {
    #[serde(rename = "SourceVideoChannel")]
    pub source_video_channel: String,
    #[serde(rename = "ReplayChannelList")]
    pub replay_channel_list: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ReplaySettingsType {
    #[serde(rename = "IsStartStopReplaySupported")]
    pub is_start_stop_replay_supported: bool,
    #[serde(rename = "IsPauseResumeReplaySupported")]
    pub is_pause_resume_replay_supported: bool,
    #[serde(rename = "IsStepReplaySupported")]
    pub is_step_replay_supported: bool,
    #[serde(rename = "SupportedReplayChannels")]
    pub supported_replay_channels: SupportedReplayChannelsListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ReplayTimelineType {
    #[serde(rename = "SourceVideoChannel")]
    pub source_video_channel: String,
    #[serde(rename = "IntervalList")]
    pub interval_list: crate::common::TimeIntervalListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ReplayChannelInfoType {
    #[serde(rename = "SourceVideoChannel")]
    pub source_video_channel: String,
    #[serde(rename = "ReplayVideoChannel")]
    pub replay_video_channel: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ReplayStatusType {
    #[serde(rename = "ReplayTimelines")]
    pub replay_timelines: ReplayTimelineListType,
    #[serde(rename = "InProgressReplays")]
    pub in_progress_replays: ReplayChannelInfoListType,
    #[serde(rename = "RunningReplayChannels")]
    pub running_replay_channels: crate::common::StringListType,
    #[serde(rename = "PausedReplayChannels")]
    pub paused_replay_channels: crate::common::StringListType,
    #[serde(rename = "LoopingReplayChannels")]
    pub looping_replay_channels: crate::common::StringListType,
}

pub mod replay_loop_mode {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "No_Loop")]
        No_Loop,
        #[serde(rename = "Infinite_Loop")]
        Infinite_Loop,
    }

}

pub mod replay_start_mode {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Play")]
        Play,
        #[serde(rename = "Pause")]
        Pause,
    }

}

