// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ScanDirectionOptionalType = Option<scan_direction_kind::Type>;

pub type ScanParameterOptionalType = Option<ScanParameterType>;

pub type GridOptionalType = Option<GridType>;

pub type ScanPatternOptionalType = Option<ScanPatternType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScanParameterType {
    #[serde(rename = "ScanVelocity")]
    pub scan_velocity: crate::common::LinearVelocityOptionalType,
    #[serde(rename = "ScanPointWaitTime")]
    pub scan_point_wait_time: crate::common::TimeSecondsOptionalType,
    #[serde(rename = "ReferenceOffset")]
    pub reference_offset: crate::common::PositionOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct GridType {
    #[serde(rename = "ScanSector")]
    pub scan_sector: crate::common::PositionType,
    #[serde(rename = "GridDistance")]
    pub grid_distance: crate::common::PositionOptionalType,
    #[serde(rename = "Direction")]
    pub direction: ScanDirectionOptionalType,
    #[serde(rename = "StartDirectionHorizontal")]
    pub start_direction_horizontal: crate::common::horizontal_direction::Type,
    #[serde(rename = "StartDirectionVertical")]
    pub start_direction_vertical: crate::common::vertical_direction::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScanPatternType {
    #[serde(rename = "PositionList")]
    pub position_list: crate::common::MultiPositionOptionalType,
    #[serde(rename = "GridMotion")]
    pub grid_motion: GridOptionalType,
    #[serde(rename = "SearchTime")]
    pub search_time: crate::common::TimeSecondsOptionalType,
    #[serde(rename = "ScanParameter")]
    pub scan_parameter: ScanParameterType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ActionSupportedType {
    #[serde(rename = "IsResetSupported")]
    pub is_reset_supported: bool,
    #[serde(rename = "IsPauseAutoSupported")]
    pub is_pause_auto_supported: bool,
    #[serde(rename = "IsRunAutoSupported")]
    pub is_run_auto_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScanCtrlSettingsType {
    #[serde(rename = "SupportedActions")]
    pub supported_actions: ActionSupportedType,
    #[serde(rename = "IsCmdStoreScanPatternSupported")]
    pub is_cmd_store_scan_pattern_supported: bool,
    #[serde(rename = "MaxNumberOfScanPoints")]
    pub max_number_of_scan_points: crate::common::ULongOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ScanCtrlStatusType {
    #[serde(rename = "Mode")]
    pub mode: scan_ctrl_mode::Type,
    #[serde(rename = "CurrentPatternName")]
    pub current_pattern_name: String,
    #[serde(rename = "ScanPattern")]
    pub scan_pattern: ScanPatternType,
    #[serde(rename = "NumberOfScanCycles")]
    pub number_of_scan_cycles: crate::common::ULongOptionalType,
    #[serde(rename = "NumberOfScanPoint")]
    pub number_of_scan_point: crate::common::ULongOptionalType,
}

pub mod scan_ctrl_mode {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Off")]
        Off,
        #[serde(rename = "Init")]
        Init,
        #[serde(rename = "Reset")]
        Reset,
        #[serde(rename = "Pause_Auto")]
        Pause_Auto,
        #[serde(rename = "Run_Auto")]
        Run_Auto,
        #[serde(rename = "Passive")]
        Passive,
        #[serde(rename = "Active")]
        Active,
        #[serde(rename = "Run_Auto_Swivel_In")]
        Run_Auto_Swivel_In,
    }

}

pub mod scan_direction_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Azimuth_Continuous_Elevation_Step")]
        Azimuth_Continuous_Elevation_Step,
        #[serde(rename = "Elevation_Continuous_Azimuth_Step")]
        Elevation_Continuous_Azimuth_Step,
        #[serde(rename = "Both_Continuous")]
        Both_Continuous,
        #[serde(rename = "Both_Step")]
        Both_Step,
    }

}

