// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type SectorDefinitionListType = Vec<SectorDefinitionType>;

pub type SelectionInfoListType = Vec<SelectionInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SectorType {
    #[serde(rename = "MinAzimuthRange")]
    pub min_azimuth_range: crate::common::DistanceMetersType,
    #[serde(rename = "MaxAzimuthRange")]
    pub max_azimuth_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "Azimuth")]
    pub azimuth: crate::common::AngleDegreesType,
    #[serde(rename = "AzimuthSize")]
    pub azimuth_size: crate::common::AngleDegreesType,
    #[serde(rename = "Elevation")]
    pub elevation: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "ElevationSize")]
    pub elevation_size: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "CoordinateFrame")]
    pub coordinate_frame: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SectorDefinitionType {
    #[serde(rename = "Id")]
    pub id: u32,
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Sector")]
    pub sector: SectorType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SelectionInfoType {
    #[serde(rename = "Id")]
    pub id: u32,
    #[serde(rename = "IsSelected")]
    pub is_selected: bool,
    #[serde(rename = "IsSelectable")]
    pub is_selectable: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SectorSelectionSettingsType {
    #[serde(rename = "IsCmdSelectSectorSupported")]
    pub is_cmd_select_sector_supported: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SectorSelectionStatusType {
    #[serde(rename = "SelectionList")]
    pub selection_list: SelectionInfoListType,
    #[serde(rename = "IsMultipleSectorSelectionAllowed")]
    pub is_multiple_sector_selection_allowed: bool,
}

