// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type SensorPresetListType = Vec<SensorPresetType>;

pub type ChannelListType = Vec<ChannelType>;

pub type WaveOptionalType = Option<WaveType>;

pub type AcousticDetectionOptionalType = Option<AcousticDetectionType>;

pub type FlashDetectionOptionalType = Option<FlashDetectionType>;

pub type LwsClassificationOptionalType = Option<lws_classification::Type>;

pub type ChildDetectionListType = Vec<ChildDetectionType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SensorPresetType {
    #[serde(rename = "Id")]
    pub id: crate::common::ObjectIdType,
    #[serde(rename = "Name")]
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SensorSettingsType {
    #[serde(rename = "TypeOfSensor")]
    pub type_of_sensor: crate::common::SensorType,
    #[serde(rename = "SensorName")]
    pub sensor_name: String,
    #[serde(rename = "SensorTypeName")]
    pub sensor_type_name: String,
    #[serde(rename = "Manufacturer")]
    pub manufacturer: String,
    #[serde(rename = "IsDetectionRangeSupported")]
    pub is_detection_range_supported: bool,
    #[serde(rename = "IsDetectionSizeSupported")]
    pub is_detection_size_supported: bool,
    #[serde(rename = "IsSensorTrackingSupported")]
    pub is_sensor_tracking_supported: bool,
    #[serde(rename = "IsDeleteSupported")]
    pub is_delete_supported: bool,
    #[serde(rename = "IsDeactivateSensorSupported")]
    pub is_deactivate_sensor_supported: bool,
    #[serde(rename = "IsLockOnSupported")]
    pub is_lock_on_supported: bool,
    #[serde(rename = "MinimumRange")]
    pub minimum_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "MaximumRange")]
    pub maximum_range: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "Presets")]
    pub presets: SensorPresetListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SensorStatusType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
    #[serde(rename = "SensorPosition")]
    pub sensor_position: crate::common::PositionOptionalType,
    #[serde(rename = "ActivePreset")]
    pub active_preset: crate::common::ObjectIdOptionalType,
    #[serde(rename = "IsDeactivated")]
    pub is_deactivated: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ChannelType {
    #[serde(rename = "Id")]
    pub id: u32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SensorCoverageType {
    #[serde(rename = "CoverageMode")]
    pub coverage_mode: coverage_mode_kind::Type,
    #[serde(rename = "Channels")]
    pub channels: ChannelListType,
    #[serde(rename = "Polygon")]
    pub polygon: crate::common::MultiPositionListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct WaveType {
    #[serde(rename = "Azimuth")]
    pub azimuth: crate::common::AngleDegreesType,
    #[serde(rename = "Elevation")]
    pub elevation: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "Amplitude")]
    pub amplitude: crate::common::AmplitudeDecibelsOptionalType,
    #[serde(rename = "Confidence")]
    pub confidence: crate::common::PercentOptionalType,
    #[serde(rename = "DetectionTime")]
    pub detection_time: crate::common::TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AcousticDetectionType {
    #[serde(rename = "WaveDetection")]
    pub wave_detection: wave_detection_kind::Type,
    #[serde(rename = "MachWave")]
    pub mach_wave: WaveOptionalType,
    #[serde(rename = "SourceWave")]
    pub source_wave: WaveOptionalType,
    #[serde(rename = "TimeBetweenMachAndSourceWave")]
    pub time_between_mach_and_source_wave: crate::common::TimeIntervalOptionalType,
    #[serde(rename = "WaveWidth")]
    pub wave_width: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "TrajectoryDistance")]
    pub trajectory_distance: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "SourceDistance")]
    pub source_distance: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "NumberOfDetections")]
    pub number_of_detections: crate::common::ULongOptionalType,
    #[serde(rename = "Azimuth1")]
    pub azimuth1: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "Azimuth2")]
    pub azimuth2: crate::common::AngleDegreesOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FlashDetectionType {
    #[serde(rename = "Position")]
    pub position: crate::common::PixelPoint2DType,
    #[serde(rename = "Size")]
    pub size: crate::common::PixelRectSizeType,
    #[serde(rename = "Timestamp")]
    pub timestamp: crate::common::TimeType,
    #[serde(rename = "FrameIndex")]
    pub frame_index: crate::common::ULongOptionalType,
    #[serde(rename = "FlashDuration")]
    pub flash_duration: crate::common::TimeSecondsType,
    #[serde(rename = "ScaledIntensity")]
    pub scaled_intensity: crate::common::PercentType,
    #[serde(rename = "ScaledIntensityRate")]
    pub scaled_intensity_rate: crate::common::PercentType,
    #[serde(rename = "Confidence")]
    pub confidence: crate::common::PercentType,
    #[serde(rename = "FlashType")]
    pub flash_type: i32,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ChildDetectionType {
    #[serde(rename = "TypeOfDetection")]
    pub type_of_detection: crate::common::DetectionType,
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationListType,
    #[serde(rename = "ObjectPositionList")]
    pub object_position_list: crate::common::PositionListType,
    #[serde(rename = "ObjectVelocityList")]
    pub object_velocity_list: crate::common::LinearVelocityListType,
    #[serde(rename = "ObjectDimensions")]
    pub object_dimensions: crate::common::ObjectDimensionsOptionalType,
    #[serde(rename = "RangeMeasurementList")]
    pub range_measurement_list: crate::laser_range_finder::RangeMeasurementListType,
    #[serde(rename = "AcousticDetection")]
    pub acoustic_detection: AcousticDetectionOptionalType,
    #[serde(rename = "FlashDetection")]
    pub flash_detection: FlashDetectionOptionalType,
    #[serde(rename = "LwsClassification")]
    pub lws_classification: LwsClassificationOptionalType,
    #[serde(rename = "VideoTrackedObject")]
    pub video_tracked_object: crate::video_tracker::VtObjectOptionalType,
    #[serde(rename = "IsLockedOn")]
    pub is_locked_on: crate::common::BooleanOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SensorDetectionType {
    #[serde(rename = "TypeOfDetection")]
    pub type_of_detection: crate::common::DetectionType,
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityType,
    #[serde(rename = "Classification")]
    pub classification: crate::common::ObjectClassificationListType,
    #[serde(rename = "ObjectPositionList")]
    pub object_position_list: crate::common::PositionListType,
    #[serde(rename = "ObjectVelocityList")]
    pub object_velocity_list: crate::common::LinearVelocityListType,
    #[serde(rename = "ObjectDimensions")]
    pub object_dimensions: crate::common::ObjectDimensionsOptionalType,
    #[serde(rename = "RangeMeasurementList")]
    pub range_measurement_list: crate::laser_range_finder::RangeMeasurementListType,
    #[serde(rename = "AcousticDetection")]
    pub acoustic_detection: AcousticDetectionOptionalType,
    #[serde(rename = "FlashDetection")]
    pub flash_detection: FlashDetectionOptionalType,
    #[serde(rename = "LwsClassification")]
    pub lws_classification: LwsClassificationOptionalType,
    #[serde(rename = "VideoTrackedObject")]
    pub video_tracked_object: crate::video_tracker::VtObjectOptionalType,
    #[serde(rename = "IsLockedOn")]
    pub is_locked_on: crate::common::BooleanOptionalType,
    #[serde(rename = "ChildDetections")]
    pub child_detections: ChildDetectionListType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

pub mod coverage_mode_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "Covered")]
        Covered,
        #[serde(rename = "Uncovered")]
        Uncovered,
        #[serde(rename = "Blocked")]
        Blocked,
        #[serde(rename = "Suppressed")]
        Suppressed,
        #[serde(rename = "EmissionControl")]
        EmissionControl,
    }

}

pub mod wave_detection_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "MachWave")]
        MachWave,
        #[serde(rename = "SourceWave")]
        SourceWave,
        #[serde(rename = "MachWave_SourceWave")]
        MachWave_SourceWave,
        #[serde(rename = "MachWave_No_SourceWave")]
        MachWave_No_SourceWave,
    }

}

pub mod lws_classification {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Initial")]
        Initial,
        #[serde(rename = "In_Progress")]
        In_Progress,
        #[serde(rename = "Unknown")]
        Unknown,
        #[serde(rename = "Single_Pulse")]
        Single_Pulse,
        #[serde(rename = "Multiple_Pulse")]
        Multiple_Pulse,
        #[serde(rename = "Beam_Rider")]
        Beam_Rider,
        #[serde(rename = "Designator")]
        Designator,
    }

}

