// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type GainOptionalType = Option<GainType>;

pub type ModulationOptionalType = Option<ModulationType>;

pub type ThresholdingOptionalType = Option<ThresholdingType>;

pub type FftOptionalType = Option<FftType>;

pub type SubchannelListType = Vec<SubchannelType>;

pub type ChannelListType = Vec<ChannelType>;

pub type HfComponentListType = Vec<HfComponentType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct GainType {
    #[serde(rename = "Mode")]
    pub mode: gain_kind::Type,
    #[serde(rename = "Value")]
    pub value: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ModulationType {
    #[serde(rename = "Type")]
    pub r#type: modulation_kind::Type,
    #[serde(rename = "IsAlcActive")]
    pub is_alc_active: crate::common::BooleanOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ThresholdingType {
    #[serde(rename = "Type")]
    pub r#type: thresholding_kind::Type,
    #[serde(rename = "Threshold")]
    pub threshold: crate::common::PowerLevelDecibelWattsOptionalType,
    #[serde(rename = "CorrelatedNoiseFloorOffset")]
    pub correlated_noise_floor_offset: crate::common::PowerLevelDecibelWattsOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FftType {
    #[serde(rename = "NumberOfSamples")]
    pub number_of_samples: i32,
    #[serde(rename = "MaximumUpdateFrequency")]
    pub maximum_update_frequency: crate::common::FrequencyHertzType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SoiType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "Frequency")]
    pub frequency: crate::common::FrequencyHertzType,
    #[serde(rename = "DetectionBandwidth")]
    pub detection_bandwidth: crate::common::FrequencyHertzType,
    #[serde(rename = "Demodulation")]
    pub demodulation: ModulationType,
    #[serde(rename = "Thresholding")]
    pub thresholding: ThresholdingType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BandScanType {
    #[serde(rename = "StartFrequency")]
    pub start_frequency: crate::common::FrequencyHertzType,
    #[serde(rename = "FrequencyStepsize")]
    pub frequency_stepsize: crate::common::FrequencyHertzType,
    #[serde(rename = "NumberOfFrequencySteps")]
    pub number_of_frequency_steps: u32,
    #[serde(rename = "Bandwidth")]
    pub bandwidth: crate::common::FrequencyHertzType,
    #[serde(rename = "Demodulation")]
    pub demodulation: ModulationOptionalType,
    #[serde(rename = "Thresholding")]
    pub thresholding: ThresholdingOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SubchannelType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "Bandwidth")]
    pub bandwidth: crate::common::FrequencyHertzOptionalType,
    #[serde(rename = "FftProperties")]
    pub fft_properties: FftOptionalType,
    #[serde(rename = "Modulation")]
    pub modulation: ModulationOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ChannelType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "DigitalGain")]
    pub digital_gain: GainOptionalType,
    #[serde(rename = "FftProperties")]
    pub fft_properties: FftOptionalType,
    #[serde(rename = "SubchannelList")]
    pub subchannel_list: SubchannelListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct HfComponentType {
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "Type")]
    pub r#type: hf_component_kind::Type,
    #[serde(rename = "CentreFrequency")]
    pub centre_frequency: crate::common::FrequencyHertzOptionalType,
    #[serde(rename = "AnalogueGain")]
    pub analogue_gain: GainOptionalType,
    #[serde(rename = "FftProperties")]
    pub fft_properties: FftOptionalType,
    #[serde(rename = "ChannelList")]
    pub channel_list: ChannelListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SignalProcessingSettingsType {
    #[serde(rename = "HfComponentList")]
    pub hf_component_list: HfComponentListType,
}

pub mod hf_component_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Transmitter")]
        Transmitter,
        #[serde(rename = "Receiver")]
        Receiver,
    }

}

pub mod gain_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "Slow")]
        Slow,
        #[serde(rename = "Medium")]
        Medium,
        #[serde(rename = "Fast")]
        Fast,
    }

}

pub mod modulation_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "FM")]
        FM,
        #[serde(rename = "FM_Squelch")]
        FM_Squelch,
        #[serde(rename = "AM")]
        AM,
        #[serde(rename = "IQ")]
        IQ,
        #[serde(rename = "LSB")]
        LSB,
        #[serde(rename = "USB")]
        USB,
    }

}

pub mod thresholding_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "Offset")]
        Offset,
        #[serde(rename = "Global")]
        Global,
    }

}

