// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type SampleListType = Vec<SampleType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct WaveformType {
    #[serde(rename = "Duration")]
    pub duration: crate::common::TimeSecondsType,
    #[serde(rename = "WaveformFunction")]
    pub waveform_function: waveform_function_kind::Type,
    #[serde(rename = "Amplitude")]
    pub amplitude: crate::common::AmplitudeScaledType,
    #[serde(rename = "StartFrequency")]
    pub start_frequency: crate::common::FrequencyHertzOptionalType,
    #[serde(rename = "EndFrequency")]
    pub end_frequency: crate::common::FrequencyHertzOptionalType,
    #[serde(rename = "Phase")]
    pub phase: crate::common::AngleRadiansOptionalType,
    #[serde(rename = "PrbsOrder")]
    pub prbs_order: crate::common::ULongOptionalType,
    #[serde(rename = "PrbsBitCount")]
    pub prbs_bit_count: crate::common::ULongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SampleType {
    #[serde(rename = "Time")]
    pub time: crate::common::TimeSecondsType,
    #[serde(rename = "Amplitude")]
    pub amplitude: crate::common::AmplitudeScaledType,
}

pub mod waveform_function_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Step")]
        Step,
        #[serde(rename = "Ramp")]
        Ramp,
        #[serde(rename = "Sine")]
        Sine,
        #[serde(rename = "Linear_Sweep")]
        Linear_Sweep,
        #[serde(rename = "Logarithmic_Sweep")]
        Logarithmic_Sweep,
        #[serde(rename = "Bidirectional_Sweep")]
        Bidirectional_Sweep,
        #[serde(rename = "Pseudorandom_Binary_Sequence")]
        Pseudorandom_Binary_Sequence,
    }

}

