// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type BatteryStatusOptionalType = Option<BatteryStatusType>;

pub type RadioConnectionStatusOptionalType = Option<RadioConnectionStatusType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BatteryStatusType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
    #[serde(rename = "Voltage")]
    pub voltage: crate::common::VoltageVoltsOptionalType,
    #[serde(rename = "Current")]
    pub current: crate::common::CurrentAmperesOptionalType,
    #[serde(rename = "TemperatureList")]
    pub temperature_list: crate::common::TemperatureKelvinsListType,
    #[serde(rename = "ScaledRemainingCharge")]
    pub scaled_remaining_charge: crate::common::PercentOptionalType,
    #[serde(rename = "RemainingRuntime")]
    pub remaining_runtime: crate::common::TimeSecondsOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RadioConnectionStatusType {
    #[serde(rename = "SignalStrength")]
    pub signal_strength: crate::common::PercentOptionalType,
    #[serde(rename = "CurrentDropRate")]
    pub current_drop_rate: crate::common::PercentOptionalType,
    #[serde(rename = "AvailableBandwidth")]
    pub available_bandwidth: crate::common::DoubleOptionalType,
    #[serde(rename = "MaxBandwidth")]
    pub max_bandwidth: crate::common::DoubleOptionalType,
    #[serde(rename = "LinkConnectionState")]
    pub link_connection_state: radio_link_connection_state::Type,
    #[serde(rename = "Jitter")]
    pub jitter: crate::common::TimeSecondsOptionalType,
    #[serde(rename = "RoundTripTime")]
    pub round_trip_time: crate::common::TimeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TeleoperationCtrlSettingsType {
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TeleoperationStatusType {
    #[serde(rename = "BatteryStatus")]
    pub battery_status: BatteryStatusOptionalType,
    #[serde(rename = "RadioConnectionStatus")]
    pub radio_connection_status: RadioConnectionStatusOptionalType,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

pub mod radio_link_connection_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Undefined")]
        Undefined,
        #[serde(rename = "Disconnected")]
        Disconnected,
        #[serde(rename = "Connecting")]
        Connecting,
        #[serde(rename = "Diconnecting")]
        Diconnecting,
        #[serde(rename = "Connected")]
        Connected,
        #[serde(rename = "Error")]
        Error,
    }

}

