// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type LightModeOptionalType = Option<light_mode::Type>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TerminalSettingsType {
    #[serde(rename = "IsConfigTerminalStateSupported")]
    pub is_config_terminal_state_supported: bool,
    #[serde(rename = "IsExitMenuSupported")]
    pub is_exit_menu_supported: bool,
    #[serde(rename = "IsSetBlackoutModeSupported")]
    pub is_set_blackout_mode_supported: bool,
    #[serde(rename = "SupportedMenuLanguages")]
    pub supported_menu_languages: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TerminalRequiredStateType {
    #[serde(rename = "BrightnessLevel")]
    pub brightness_level: crate::common::PercentOptionalType,
    #[serde(rename = "LightMode")]
    pub light_mode: LightModeOptionalType,
    #[serde(rename = "VideoChannelName")]
    pub video_channel_name: String,
    #[serde(rename = "AllowedView")]
    pub allowed_view: sight_system_view::Type,
    #[serde(rename = "EnableTracking")]
    pub enable_tracking: crate::common::BooleanOptionalType,
    #[serde(rename = "AimingMarkCenterOffset")]
    pub aiming_mark_center_offset: crate::common::PositionOptionalType,
    #[serde(rename = "IsOfflineModeEnabled")]
    pub is_offline_mode_enabled: crate::common::BooleanOptionalType,
    #[serde(rename = "IsMenuLocked")]
    pub is_menu_locked: crate::common::BooleanOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TerminalStateType {
    #[serde(rename = "OperationStatus")]
    pub operation_status: crate::common::OperationStatusType,
    #[serde(rename = "BrightnessLevel")]
    pub brightness_level: crate::common::PercentOptionalType,
    #[serde(rename = "LightMode")]
    pub light_mode: LightModeOptionalType,
    #[serde(rename = "IsBlackoutModeEnabled")]
    pub is_blackout_mode_enabled: crate::common::BooleanOptionalType,
    #[serde(rename = "VideoChannelName")]
    pub video_channel_name: String,
    #[serde(rename = "AllowedView")]
    pub allowed_view: sight_system_view::Type,
    #[serde(rename = "EnableTracking")]
    pub enable_tracking: crate::common::BooleanOptionalType,
    #[serde(rename = "AimingMarkCenterOffset")]
    pub aiming_mark_center_offset: crate::common::PositionOptionalType,
    #[serde(rename = "IsOfflineModeEnabled")]
    pub is_offline_mode_enabled: crate::common::BooleanOptionalType,
    #[serde(rename = "IsMenuLocked")]
    pub is_menu_locked: crate::common::BooleanOptionalType,
    #[serde(rename = "IsMenuShown")]
    pub is_menu_shown: crate::common::BooleanOptionalType,
    #[serde(rename = "SelectedMenuLanguage")]
    pub selected_menu_language: String,
}

pub mod light_mode {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Default_Light")]
        Default_Light,
        #[serde(rename = "Reduced_Light")]
        Reduced_Light,
        #[serde(rename = "Lamp_Test")]
        Lamp_Test,
    }

}

pub mod sight_system_view {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Free_Choice")]
        Free_Choice,
        #[serde(rename = "Only_Sight_System_Cameras")]
        Only_Sight_System_Cameras,
        #[serde(rename = "Only_Target_Sight_Camera")]
        Only_Target_Sight_Camera,
    }

}

