// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct TimeSourceType {
    #[serde(rename = "Source")]
    pub source: time_source_kind::Type,
    #[serde(rename = "Description")]
    pub description: String,
}

pub mod time_source_kind {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString, dust_dds::infrastructure::type_support::DdsType)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Unspecified")]
        Unspecified,
        #[serde(rename = "Manual")]
        Manual,
        #[serde(rename = "System_Clock")]
        System_Clock,
        #[serde(rename = "Rtc")]
        Rtc,
        #[serde(rename = "Ntp_Server")]
        Ntp_Server,
        #[serde(rename = "Ptp_Master")]
        Ptp_Master,
        #[serde(rename = "Satellite")]
        Satellite,
        #[serde(rename = "Multi_Gnss")]
        Multi_Gnss,
        #[serde(rename = "Gps")]
        Gps,
        #[serde(rename = "Qzss")]
        Qzss,
        #[serde(rename = "Beidou")]
        Beidou,
        #[serde(rename = "Galileo")]
        Galileo,
        #[serde(rename = "Glonass")]
        Glonass,
        #[serde(rename = "Radio")]
        Radio,
        #[serde(rename = "Loran_C")]
        Loran_C,
        #[serde(rename = "Cellular")]
        Cellular,
        #[serde(rename = "Internet_Service")]
        Internet_Service,
        #[serde(rename = "Bluetooth")]
        Bluetooth,
    }

}

