// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type ChannelInfoListType = Vec<ChannelInfoType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct ChannelInfoType {
    #[serde(rename = "VideoChannelName")]
    pub video_channel_name: String,
    #[serde(rename = "CameraName")]
    pub camera_name: String,
    #[serde(rename = "IsSynchronised")]
    pub is_synchronised: bool,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VmSettingsType {
    #[serde(rename = "AvailableChannelList")]
    pub available_channel_list: ChannelInfoListType,
    #[serde(rename = "IsCmdFovCouplingSupported")]
    pub is_cmd_fov_coupling_supported: bool,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VmStatusType {
    #[serde(rename = "IsFovCouplingEnabled")]
    pub is_fov_coupling_enabled: bool,
    #[serde(rename = "VideoChannel")]
    pub video_channel: ChannelInfoType,
    #[serde(rename = "AvailableVideoChannels")]
    pub available_video_channels: crate::common::StringListType,
    #[serde(rename = "IsVideoChannelChangeInProgress")]
    pub is_video_channel_change_in_progress: bool,
}

