// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type SecurityMetadataUniversalLSOptionalType = Option<SecurityMetadataUniversalLS>;

pub type SecurityMetadataLSOptionalType = Option<SecurityMetadataLS>;

pub type VFeatureLSOptionalType = Option<VFeatureLS>;

pub type VChipLSOptionalType = Option<VChipLS>;

pub type VChipLSListType = Vec<VChipLS>;

pub type VObjectLSOptionalType = Option<VObjectLS>;

pub type PixelNumberPlusRunLengthOptionalType = Option<PixelNumberPlusRunLength>;

pub type PixelNumberPlusRunLengthListType = Vec<PixelNumberPlusRunLength>;

pub type VMaskLSOptionalType = Option<VMaskLS>;

pub type AccelerationTruncationPackOptionalType = Option<AccelerationTruncationPack>;

pub type VelocityTruncationPackOptionalType = Option<VelocityTruncationPack>;

pub type LocationTruncationPackOptionalType = Option<LocationTruncationPack>;

pub type LocationTruncationPackListType = Vec<LocationTruncationPack>;

pub type BoundarySeriesOptionalType = Option<BoundarySeries>;

pub type FpaIndexPackOptionalType = Option<FpaIndexPack>;

pub type VTrackItemPackOptionalType = Option<VTrackItemPack>;

pub type VTrackItemPackListType = Vec<VTrackItemPack>;

pub type VTrackLSOptionalType = Option<VTrackLS>;

pub type VTrackerLSOptionalType = Option<VTrackerLS>;

pub type VTargetPackOptionalType = Option<VTargetPack>;

pub type VTargetPackListType = Vec<VTargetPack>;

pub type VmtiLSOptionalType = Option<VmtiLS>;

pub type VmtiLSListType = Vec<VmtiLS>;

pub type AreaOfInterestLSOptionalType = Option<AreaOfInterestLS>;

pub type AreaOfInterestLSListType = Vec<AreaOfInterestLS>;

pub type PointOfInterestLSOptionalType = Option<PointOfInterestLS>;

pub type PointOfInterestLSListType = Vec<PointOfInterestLS>;

pub type RvtLSOptionalType = Option<RvtLS>;

pub type RvtLSListType = Vec<RvtLS>;

pub type UasImageHorizonPixelPackOptionalType = Option<UasImageHorizonPixelPack>;

pub type SarMotionImageryMetadataLSOptionalType = Option<SarMotionImageryMetadataLS>;

pub type UasOffsetCornerOptionalType = Option<UasOffsetCorner>;

pub type UasCornerOptionalType = Option<UasCorner>;

pub type UasAlternatePlatformOptionalType = Option<UasAlternatePlatform>;

pub type UasSensorOptionalType = Option<UasSensor>;

pub type UasPlatformOptionalType = Option<UasPlatform>;

pub type UasTargetOptionalType = Option<UasTarget>;

pub type UasDatalinkLSOptionalType = Option<UasDatalinkLS>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SecurityMetadataUniversalLS {
    #[serde(rename = "SecurityClassification")]
    pub security_classification: crate::common::StringOptionalType,
    #[serde(rename = "ClassifyingCountryAndReleasingInstructionsCountryCodingMethod")]
    pub classifying_country_and_releasing_instructions_country_coding_method: crate::common::StringOptionalType,
    #[serde(rename = "ClassifyingCountry")]
    pub classifying_country: crate::common::StringOptionalType,
    #[serde(rename = "SecuritySciShiInformation")]
    pub security_sci_shi_information: crate::common::StringOptionalType,
    #[serde(rename = "Caveats")]
    pub caveats: crate::common::StringOptionalType,
    #[serde(rename = "ReleasingInstructions")]
    pub releasing_instructions: crate::common::StringOptionalType,
    #[serde(rename = "ClassifiedBy")]
    pub classified_by: crate::common::StringOptionalType,
    #[serde(rename = "DerivedFrom")]
    pub derived_from: crate::common::StringOptionalType,
    #[serde(rename = "ClassificationReason")]
    pub classification_reason: crate::common::StringOptionalType,
    #[serde(rename = "DeclassificationDate")]
    pub declassification_date: crate::common::StringOptionalType,
    #[serde(rename = "ClassificationAndMarkingSystem")]
    pub classification_and_marking_system: crate::common::StringOptionalType,
    #[serde(rename = "ObjectCountryCodingMethod")]
    pub object_country_coding_method: crate::common::StringOptionalType,
    #[serde(rename = "ObjectCountryCodes")]
    pub object_country_codes: crate::common::StringOptionalType,
    #[serde(rename = "ClassificationComments")]
    pub classification_comments: crate::common::StringOptionalType,
    #[serde(rename = "Umid")]
    pub umid: crate::common::StringOptionalType,
    #[serde(rename = "StreamId")]
    pub stream_id: crate::common::StringOptionalType,
    #[serde(rename = "TransportStreamId")]
    pub transport_stream_id: crate::common::StringOptionalType,
    #[serde(rename = "ItemDesignatorId")]
    pub item_designator_id: crate::common::StringOptionalType,
    #[serde(rename = "Version")]
    pub version: crate::common::ULongOptionalType,
    #[serde(rename = "ClassifyingCountryAndReleasingInstructionsCountryCodingMethodVersionDate")]
    pub classifying_country_and_releasing_instructions_country_coding_method_version_date: crate::common::StringOptionalType,
    #[serde(rename = "ObjectCountryCodingMethodVersionDate")]
    pub object_country_coding_method_version_date: crate::common::StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SecurityMetadataLS {
    #[serde(rename = "SecurityClassification")]
    pub security_classification: crate::common::ULongOptionalType,
    #[serde(rename = "ClassifyingCountryAndReleasingInstructionsCountryCodingMethod")]
    pub classifying_country_and_releasing_instructions_country_coding_method: crate::common::ULongOptionalType,
    #[serde(rename = "ClassifyingCountry")]
    pub classifying_country: crate::common::StringOptionalType,
    #[serde(rename = "SecuritySciShiInformation")]
    pub security_sci_shi_information: crate::common::StringOptionalType,
    #[serde(rename = "Caveats")]
    pub caveats: crate::common::StringOptionalType,
    #[serde(rename = "ReleasingInstructions")]
    pub releasing_instructions: crate::common::StringOptionalType,
    #[serde(rename = "ClassifiedBy")]
    pub classified_by: crate::common::StringOptionalType,
    #[serde(rename = "DerivedFrom")]
    pub derived_from: crate::common::StringOptionalType,
    #[serde(rename = "ClassificationReason")]
    pub classification_reason: crate::common::StringOptionalType,
    #[serde(rename = "DeclassificationDate")]
    pub declassification_date: crate::common::StringOptionalType,
    #[serde(rename = "ClassificationAndMarkingSystem")]
    pub classification_and_marking_system: crate::common::StringOptionalType,
    #[serde(rename = "ObjectCountryCodingMethod")]
    pub object_country_coding_method: crate::common::ULongOptionalType,
    #[serde(rename = "ObjectCountryCodes")]
    pub object_country_codes: crate::common::StringOptionalType,
    #[serde(rename = "ClassificationComments")]
    pub classification_comments: crate::common::StringOptionalType,
    #[serde(rename = "Umid")]
    pub umid: crate::common::StringOptionalType,
    #[serde(rename = "StreamId")]
    pub stream_id: crate::common::StringOptionalType,
    #[serde(rename = "TransportStreamId")]
    pub transport_stream_id: crate::common::StringOptionalType,
    #[serde(rename = "ItemDesignatorId")]
    pub item_designator_id: crate::common::StringOptionalType,
    #[serde(rename = "Version")]
    pub version: crate::common::ULongOptionalType,
    #[serde(rename = "ClassifyingCountryAndReleasingInstructionsCountryCodingMethodVersionDate")]
    pub classifying_country_and_releasing_instructions_country_coding_method_version_date: crate::common::StringOptionalType,
    #[serde(rename = "ObjectCountryCodingMethodVersionDate")]
    pub object_country_coding_method_version_date: crate::common::StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VFeatureLS {
    #[serde(rename = "Schema")]
    pub schema: crate::common::StringOptionalType,
    #[serde(rename = "SchemaFeature")]
    pub schema_feature: crate::common::StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VChipLS {
    #[serde(rename = "ImageType")]
    pub image_type: crate::common::StringOptionalType,
    #[serde(rename = "ImageUri")]
    pub image_uri: crate::common::StringOptionalType,
    #[serde(rename = "EmbeddedImage")]
    pub embedded_image: crate::common::ByteSeqType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VObjectLS {
    #[serde(rename = "Ontology")]
    pub ontology: crate::common::StringOptionalType,
    #[serde(rename = "OntologyClass")]
    pub ontology_class: crate::common::StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PixelNumberPlusRunLength {
    #[serde(rename = "PixelNumber")]
    pub pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "RunLength")]
    pub run_length: crate::common::ULongLongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VMaskLS {
    #[serde(rename = "Polygon")]
    pub polygon: crate::common::ULongLongListType,
    #[serde(rename = "BitMask")]
    pub bit_mask: PixelNumberPlusRunLengthListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AccelerationTruncationPack {
    #[serde(rename = "EastComponent")]
    pub east_component: crate::common::DoubleOptionalType,
    #[serde(rename = "NorthComponent")]
    pub north_component: crate::common::DoubleOptionalType,
    #[serde(rename = "UpComponent")]
    pub up_component: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaEast")]
    pub sigma_east: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaNorth")]
    pub sigma_north: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaUp")]
    pub sigma_up: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoEastNorth")]
    pub rho_east_north: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoEastUp")]
    pub rho_east_up: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoNorthUp")]
    pub rho_north_up: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VelocityTruncationPack {
    #[serde(rename = "EastComponent")]
    pub east_component: crate::common::DoubleOptionalType,
    #[serde(rename = "NorthComponent")]
    pub north_component: crate::common::DoubleOptionalType,
    #[serde(rename = "UpComponent")]
    pub up_component: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaEast")]
    pub sigma_east: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaNorth")]
    pub sigma_north: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaUp")]
    pub sigma_up: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoEastNorth")]
    pub rho_east_north: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoEastUp")]
    pub rho_east_up: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoNorthUp")]
    pub rho_north_up: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LocationTruncationPack {
    #[serde(rename = "Latitude")]
    pub latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "Longitude")]
    pub longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "Height")]
    pub height: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaEast")]
    pub sigma_east: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaNorth")]
    pub sigma_north: crate::common::DoubleOptionalType,
    #[serde(rename = "SigmaUp")]
    pub sigma_up: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoEastNorth")]
    pub rho_east_north: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoEastUp")]
    pub rho_east_up: crate::common::DoubleOptionalType,
    #[serde(rename = "RhoNorthUp")]
    pub rho_north_up: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct BoundarySeries {
    #[serde(rename = "LocationPack")]
    pub location_pack: LocationTruncationPackListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct FpaIndexPack {
    #[serde(rename = "FpaRow")]
    pub fpa_row: crate::common::ULongOptionalType,
    #[serde(rename = "FpaColumn")]
    pub fpa_column: crate::common::ULongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VTrackItemPack {
    #[serde(rename = "TargetIdNumber")]
    pub target_id_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "TargetTimeStamp")]
    pub target_time_stamp: crate::common::ULongLongOptionalType,
    #[serde(rename = "TargetCentroidPixelNumber")]
    pub target_centroid_pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "TargetCentroidPixelRow")]
    pub target_centroid_pixel_row: crate::common::ULongLongOptionalType,
    #[serde(rename = "TargetCentroidPixelColumn")]
    pub target_centroid_pixel_column: crate::common::ULongLongOptionalType,
    #[serde(rename = "BoundingBoxTopLeftPixelNumber")]
    pub bounding_box_top_left_pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "BoundingBoxBottomRightPixelNumber")]
    pub bounding_box_bottom_right_pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "TargetPriority")]
    pub target_priority: crate::common::UShortOptionalType,
    #[serde(rename = "TargetConfidenceLevel")]
    pub target_confidence_level: crate::common::UShortOptionalType,
    #[serde(rename = "NewDetectionFlagTargetHistory")]
    pub new_detection_flag_target_history: crate::common::UShortOptionalType,
    #[serde(rename = "PercentageOfTargetPixels")]
    pub percentage_of_target_pixels: crate::common::UShortOptionalType,
    #[serde(rename = "TargetColor")]
    pub target_color: crate::common::ULongOptionalType,
    #[serde(rename = "TargetIntensity")]
    pub target_intensity: crate::common::ULongOptionalType,
    #[serde(rename = "TargetLocation")]
    pub target_location: LocationTruncationPackOptionalType,
    #[serde(rename = "TargetBoundary")]
    pub target_boundary: BoundarySeriesOptionalType,
    #[serde(rename = "Velocity")]
    pub velocity: VelocityTruncationPackOptionalType,
    #[serde(rename = "Acceleration")]
    pub acceleration: AccelerationTruncationPackOptionalType,
    #[serde(rename = "FpaIndex")]
    pub fpa_index: FpaIndexPackOptionalType,
    #[serde(rename = "MotionImageryFrameNumber")]
    pub motion_imagery_frame_number: crate::common::ULongOptionalType,
    #[serde(rename = "MotionImageryId")]
    pub motion_imagery_id: crate::common::StringOptionalType,
    #[serde(rename = "FrameWidth")]
    pub frame_width: crate::common::ULongOptionalType,
    #[serde(rename = "FrameHeight")]
    pub frame_height: crate::common::ULongOptionalType,
    #[serde(rename = "SensorHorizontalFieldOfView")]
    pub sensor_horizontal_field_of_view: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorVerticalFieldOfView")]
    pub sensor_vertical_field_of_view: crate::common::DoubleOptionalType,
    #[serde(rename = "MotionImageryUrl")]
    pub motion_imagery_url: crate::common::StringOptionalType,
    #[serde(rename = "VMaskLs")]
    pub v_mask_ls: VMaskLSOptionalType,
    #[serde(rename = "VObject")]
    pub v_object: VObjectLSOptionalType,
    #[serde(rename = "VFeatureLs")]
    pub v_feature_ls: VFeatureLSOptionalType,
    #[serde(rename = "VChip")]
    pub v_chip: VChipLSOptionalType,
    #[serde(rename = "VChipSeries")]
    pub v_chip_series: VChipLSListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VTrackLS {
    #[serde(rename = "Checksum")]
    pub checksum: crate::common::UShortOptionalType,
    #[serde(rename = "TrackTimeStamp")]
    pub track_time_stamp: crate::common::ULongLongOptionalType,
    #[serde(rename = "TrackId")]
    pub track_id: crate::common::StringOptionalType,
    #[serde(rename = "TrackStatus")]
    pub track_status: crate::common::UShortOptionalType,
    #[serde(rename = "TrackStartTime")]
    pub track_start_time: crate::common::ULongLongOptionalType,
    #[serde(rename = "TrackEndTime")]
    pub track_end_time: crate::common::ULongLongOptionalType,
    #[serde(rename = "TrackBoundingBox")]
    pub track_bounding_box: BoundarySeriesOptionalType,
    #[serde(rename = "TrackerAlgorithm")]
    pub tracker_algorithm: crate::common::StringOptionalType,
    #[serde(rename = "TrackConfidence")]
    pub track_confidence: crate::common::UShortOptionalType,
    #[serde(rename = "VmtiSystemNameDescription")]
    pub vmti_system_name_description: crate::common::StringOptionalType,
    #[serde(rename = "VmtiLsVersionNumber")]
    pub vmti_ls_version_number: crate::common::UShortOptionalType,
    #[serde(rename = "VmtiSourceSensor")]
    pub vmti_source_sensor: crate::common::StringOptionalType,
    #[serde(rename = "NumberOfTrackpoints")]
    pub number_of_trackpoints: crate::common::ULongLongOptionalType,
    #[serde(rename = "VTrackItemSeries")]
    pub v_track_item_series: VTrackItemPackListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VTrackerLS {
    #[serde(rename = "TrackId")]
    pub track_id: crate::common::StringOptionalType,
    #[serde(rename = "DetectionStatus")]
    pub detection_status: crate::common::UShortOptionalType,
    #[serde(rename = "StartTimestamp")]
    pub start_timestamp: crate::common::ULongLongOptionalType,
    #[serde(rename = "EndTimeStamp")]
    pub end_time_stamp: crate::common::ULongLongOptionalType,
    #[serde(rename = "BoundingBox")]
    pub bounding_box: BoundarySeriesOptionalType,
    #[serde(rename = "Algorithm")]
    pub algorithm: crate::common::StringOptionalType,
    #[serde(rename = "Confidence")]
    pub confidence: crate::common::UShortOptionalType,
    #[serde(rename = "NumberOfTrackPoints")]
    pub number_of_track_points: crate::common::UShortOptionalType,
    #[serde(rename = "Locus")]
    pub locus: LocationTruncationPackListType,
    #[serde(rename = "Velocity")]
    pub velocity: VelocityTruncationPackOptionalType,
    #[serde(rename = "Acceleration")]
    pub acceleration: AccelerationTruncationPackOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VTargetPack {
    #[serde(rename = "TargetIdNumber")]
    pub target_id_number: crate::common::StringOptionalType,
    #[serde(rename = "TargetCentroidPixelNumber")]
    pub target_centroid_pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "BoundingBoxTopLeftPixelNumber")]
    pub bounding_box_top_left_pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "BoundingBoxBottomRightPixelNumber")]
    pub bounding_box_bottom_right_pixel_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "TargetPriority")]
    pub target_priority: crate::common::UShortOptionalType,
    #[serde(rename = "TargetConfidenceLevel")]
    pub target_confidence_level: crate::common::UShortOptionalType,
    #[serde(rename = "NewDetectionFlagTargetHistory")]
    pub new_detection_flag_target_history: crate::common::UShortOptionalType,
    #[serde(rename = "PercentageOfTargetPixels")]
    pub percentage_of_target_pixels: crate::common::UShortOptionalType,
    #[serde(rename = "TargetColor")]
    pub target_color: crate::common::ULongOptionalType,
    #[serde(rename = "TargetIntensity")]
    pub target_intensity: crate::common::ULongOptionalType,
    #[serde(rename = "TargetLocationLatitudeOffset")]
    pub target_location_latitude_offset: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetLocationLongitudeOffset")]
    pub target_location_longitude_offset: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetHeight")]
    pub target_height: crate::common::DoubleOptionalType,
    #[serde(rename = "BoundingBoxTopLeftLatitudeOffset")]
    pub bounding_box_top_left_latitude_offset: crate::common::DoubleOptionalType,
    #[serde(rename = "BoundingBoxTopLeftLongitudeOffset")]
    pub bounding_box_top_left_longitude_offset: crate::common::DoubleOptionalType,
    #[serde(rename = "BoundingBoxBottomRightLatitudeOffset")]
    pub bounding_box_bottom_right_latitude_offset: crate::common::DoubleOptionalType,
    #[serde(rename = "BoundingBoxbottomRightLongitudeOffset")]
    pub bounding_boxbottom_right_longitude_offset: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetLocation")]
    pub target_location: LocationTruncationPackOptionalType,
    #[serde(rename = "TargetBoundary")]
    pub target_boundary: BoundarySeriesOptionalType,
    #[serde(rename = "TargetCentroidPixelRow")]
    pub target_centroid_pixel_row: crate::common::ULongOptionalType,
    #[serde(rename = "TargetCentroidPixelColumn")]
    pub target_centroid_pixel_column: crate::common::ULongOptionalType,
    #[serde(rename = "FpaIndex")]
    pub fpa_index: FpaIndexPackOptionalType,
    #[serde(rename = "VMaskLs")]
    pub v_mask_ls: VMaskLSOptionalType,
    #[serde(rename = "VObjectLs")]
    pub v_object_ls: VObjectLSOptionalType,
    #[serde(rename = "VFeatureLs")]
    pub v_feature_ls: VFeatureLSOptionalType,
    #[serde(rename = "VTrackerLs")]
    pub v_tracker_ls: VTrackerLSOptionalType,
    #[serde(rename = "VChip")]
    pub v_chip: VChipLSOptionalType,
    #[serde(rename = "VChipSeries")]
    pub v_chip_series: VChipLSListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VmtiLS {
    #[serde(rename = "Checksum")]
    pub checksum: crate::common::UShortOptionalType,
    #[serde(rename = "PrecisionTimeStampPosixMicroseconds")]
    pub precision_time_stamp_posix_microseconds: crate::common::ULongLongOptionalType,
    #[serde(rename = "VmtiSystemNameDescription")]
    pub vmti_system_name_description: crate::common::StringOptionalType,
    #[serde(rename = "VmtiLsVersionnumber")]
    pub vmti_ls_versionnumber: crate::common::UShortOptionalType,
    #[serde(rename = "TotalNumberOfTargetsDetectedInTheFrame")]
    pub total_number_of_targets_detected_in_the_frame: crate::common::ULongOptionalType,
    #[serde(rename = "NumberOfReportedTargets")]
    pub number_of_reported_targets: crate::common::ULongOptionalType,
    #[serde(rename = "MotionImageryFrameNumber")]
    pub motion_imagery_frame_number: crate::common::ULongOptionalType,
    #[serde(rename = "FrameWidth")]
    pub frame_width: crate::common::ULongOptionalType,
    #[serde(rename = "FrameHeight")]
    pub frame_height: crate::common::ULongOptionalType,
    #[serde(rename = "VmtiSourceSensor")]
    pub vmti_source_sensor: crate::common::StringOptionalType,
    #[serde(rename = "VmtiSensorHorizontalFieldOfView")]
    pub vmti_sensor_horizontal_field_of_view: crate::common::DoubleOptionalType,
    #[serde(rename = "VmtiSensorVerticalFieldOfView")]
    pub vmti_sensor_vertical_field_of_view: crate::common::DoubleOptionalType,
    #[serde(rename = "MotionImageryId")]
    pub motion_imagery_id: crate::common::StringOptionalType,
    #[serde(rename = "VTargetSeries")]
    pub v_target_series: VTargetPackListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AreaOfInterestLS {
    #[serde(rename = "PoiAoiNumber")]
    pub poi_aoi_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "CornerLatitudePoint1")]
    pub corner_latitude_point1: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLongitudePoint1")]
    pub corner_longitude_point1: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLatitudePoint3")]
    pub corner_latitude_point3: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLongitudePoint3")]
    pub corner_longitude_point3: crate::common::DoubleOptionalType,
    #[serde(rename = "PoiAoiType")]
    pub poi_aoi_type: crate::common::ULongLongOptionalType,
    #[serde(rename = "PoiAoiText")]
    pub poi_aoi_text: crate::common::StringOptionalType,
    #[serde(rename = "PoiAoiSourceId")]
    pub poi_aoi_source_id: crate::common::StringOptionalType,
    #[serde(rename = "PoiAoiLabel")]
    pub poi_aoi_label: crate::common::StringOptionalType,
    #[serde(rename = "OperationId")]
    pub operation_id: crate::common::StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct PointOfInterestLS {
    #[serde(rename = "PoiAoiNumber")]
    pub poi_aoi_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "PoiLatitude")]
    pub poi_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "PoiLongitude")]
    pub poi_longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "PoiAltitude")]
    pub poi_altitude: crate::common::DoubleOptionalType,
    #[serde(rename = "PoiAoiType")]
    pub poi_aoi_type: crate::common::ULongLongOptionalType,
    #[serde(rename = "PoiAoiText")]
    pub poi_aoi_text: crate::common::StringOptionalType,
    #[serde(rename = "PoiSourceIcon")]
    pub poi_source_icon: crate::common::StringOptionalType,
    #[serde(rename = "PoiAoiSourceId")]
    pub poi_aoi_source_id: crate::common::StringOptionalType,
    #[serde(rename = "PoiAoiLabel")]
    pub poi_aoi_label: crate::common::StringOptionalType,
    #[serde(rename = "OperationId")]
    pub operation_id: crate::common::StringOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct RvtLS {
    #[serde(rename = "Crc32")]
    pub crc32: crate::common::ULongLongOptionalType,
    #[serde(rename = "UserDefinedTimestampMicrosecondsSince1970")]
    pub user_defined_timestamp_microseconds_since1970: crate::common::ULongLongOptionalType,
    #[serde(rename = "PlatformTrueAirspeed")]
    pub platform_true_airspeed: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformIndicatedAirspeed")]
    pub platform_indicated_airspeed: crate::common::DoubleOptionalType,
    #[serde(rename = "TelemetryAccuracyIndicator")]
    pub telemetry_accuracy_indicator: crate::common::DoubleOptionalType,
    #[serde(rename = "FragCircleRadius")]
    pub frag_circle_radius: crate::common::DoubleOptionalType,
    #[serde(rename = "FrameCode")]
    pub frame_code: crate::common::DoubleOptionalType,
    #[serde(rename = "UasLsVersionNumber")]
    pub uas_ls_version_number: crate::common::ULongLongOptionalType,
    #[serde(rename = "VideoDataRate")]
    pub video_data_rate: crate::common::DoubleOptionalType,
    #[serde(rename = "DigitalVideoFileFormat")]
    pub digital_video_file_format: crate::common::StringOptionalType,
    #[serde(rename = "UserDefinedLs")]
    pub user_defined_ls: crate::common::PropertyListType,
    #[serde(rename = "PointOfInterest")]
    pub point_of_interest: PointOfInterestLSListType,
    #[serde(rename = "AreaOfInterest")]
    pub area_of_interest: AreaOfInterestLSListType,
    #[serde(rename = "MgrsZone")]
    pub mgrs_zone: crate::common::ULongOptionalType,
    #[serde(rename = "MgrsLatitudeBandAndGridSquare")]
    pub mgrs_latitude_band_and_grid_square: crate::common::StringOptionalType,
    #[serde(rename = "MgrsEasting")]
    pub mgrs_easting: crate::common::ULongOptionalType,
    #[serde(rename = "MgrsNorthing")]
    pub mgrs_northing: crate::common::ULongOptionalType,
    #[serde(rename = "MgrsZoneSecondValue")]
    pub mgrs_zone_second_value: crate::common::ULongOptionalType,
    #[serde(rename = "MgrsLatitudeBandandGridSquareSecondValue")]
    pub mgrs_latitude_bandand_grid_square_second_value: crate::common::StringOptionalType,
    #[serde(rename = "MgrsEastingSecondValue")]
    pub mgrs_easting_second_value: crate::common::ULongOptionalType,
    #[serde(rename = "MgrsNorthingSecondValue")]
    pub mgrs_northing_second_value: crate::common::ULongOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasImageHorizonPixelPack {
    #[serde(rename = "StartX0")]
    pub start_x0: crate::common::ULongLongOptionalType,
    #[serde(rename = "StartY0")]
    pub start_y0: crate::common::ULongLongOptionalType,
    #[serde(rename = "EndX1")]
    pub end_x1: crate::common::ULongLongOptionalType,
    #[serde(rename = "EndY1")]
    pub end_y1: crate::common::ULongLongOptionalType,
    #[serde(rename = "StartLatitude")]
    pub start_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "StartLongitude")]
    pub start_longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "EndLatitude")]
    pub end_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "EndLongitude")]
    pub end_longitude: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct SarMotionImageryMetadataLS {
    #[serde(rename = "GrazingAngle")]
    pub grazing_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "GroundPlaneSquintAngle")]
    pub ground_plane_squint_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "LookDirection")]
    pub look_direction: crate::common::UShortOptionalType,
    #[serde(rename = "ImagePlane")]
    pub image_plane: crate::common::UShortOptionalType,
    #[serde(rename = "RangeResolution")]
    pub range_resolution: crate::common::DoubleOptionalType,
    #[serde(rename = "CrossRangeResolution")]
    pub cross_range_resolution: crate::common::DoubleOptionalType,
    #[serde(rename = "RangeImagePlanePixelSize")]
    pub range_image_plane_pixel_size: crate::common::DoubleOptionalType,
    #[serde(rename = "CrossRangeImagePlanePixelSize")]
    pub cross_range_image_plane_pixel_size: crate::common::DoubleOptionalType,
    #[serde(rename = "ImageRows")]
    pub image_rows: crate::common::ULongLongOptionalType,
    #[serde(rename = "ImageColumns")]
    pub image_columns: crate::common::ULongLongOptionalType,
    #[serde(rename = "RangeDirectionAngleRelativeToTrueNorth")]
    pub range_direction_angle_relative_to_true_north: crate::common::DoubleOptionalType,
    #[serde(rename = "TrueNorthDirectionRelativeToTopImageEdge")]
    pub true_north_direction_relative_to_top_image_edge: crate::common::DoubleOptionalType,
    #[serde(rename = "RangeLayoverAngleRelativeToTrueNorth")]
    pub range_layover_angle_relative_to_true_north: crate::common::DoubleOptionalType,
    #[serde(rename = "GroundApertureAngularExtent")]
    pub ground_aperture_angular_extent: crate::common::DoubleOptionalType,
    #[serde(rename = "ApertureDuration")]
    pub aperture_duration: crate::common::ULongLongOptionalType,
    #[serde(rename = "GroundTrackAngle")]
    pub ground_track_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "MinimumDetectableVelocity")]
    pub minimum_detectable_velocity: crate::common::DoubleOptionalType,
    #[serde(rename = "TruePulseRepetitionFrequency")]
    pub true_pulse_repetition_frequency: crate::common::DoubleOptionalType,
    #[serde(rename = "PulseRepetitionFrequencyScaleFactor")]
    pub pulse_repetition_frequency_scale_factor: crate::common::DoubleOptionalType,
    #[serde(rename = "TransmitRfCenterFrequency")]
    pub transmit_rf_center_frequency: crate::common::DoubleOptionalType,
    #[serde(rename = "TransmitRfBandwidth")]
    pub transmit_rf_bandwidth: crate::common::DoubleOptionalType,
    #[serde(rename = "RadarCrossSectionScaleFactorPolynomial")]
    pub radar_cross_section_scale_factor_polynomial: crate::common::DoubleMatrixType,
    #[serde(rename = "ReferenceFramePrecisionTimeStamp")]
    pub reference_frame_precision_time_stamp: crate::common::ULongLongOptionalType,
    #[serde(rename = "ReferenceFrameGrazingAngle")]
    pub reference_frame_grazing_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "ReferenceFrameGroundPlaneSquintAngle")]
    pub reference_frame_ground_plane_squint_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "ReferenceFrameRangeDirectionAngleRelativeToTrueNorth")]
    pub reference_frame_range_direction_angle_relative_to_true_north: crate::common::DoubleOptionalType,
    #[serde(rename = "ReferenceFrameRangeLayoverAngleRelativeToTrueNorth")]
    pub reference_frame_range_layover_angle_relative_to_true_north: crate::common::DoubleOptionalType,
    #[serde(rename = "DocumentVersion")]
    pub document_version: crate::common::UShortOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasOffsetCorner {
    #[serde(rename = "OffsetCornerLatitudePoint1")]
    pub offset_corner_latitude_point1: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLongitudePoint1")]
    pub offset_corner_longitude_point1: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLatitudePoint2")]
    pub offset_corner_latitude_point2: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLongitudePoint2")]
    pub offset_corner_longitude_point2: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLatitudePoint3")]
    pub offset_corner_latitude_point3: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLongitudePoint3")]
    pub offset_corner_longitude_point3: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLatitudePoint4")]
    pub offset_corner_latitude_point4: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCornerLongitudePoint4")]
    pub offset_corner_longitude_point4: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasCorner {
    #[serde(rename = "CornerLatitudePoint1Full")]
    pub corner_latitude_point1_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLongitudePoint1Full")]
    pub corner_longitude_point1_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerlatitudePoint2Full")]
    pub cornerlatitude_point2_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLongitudePoint2Full")]
    pub corner_longitude_point2_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLatitudePoint3Full")]
    pub corner_latitude_point3_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLongitudePoint3Full")]
    pub corner_longitude_point3_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLatitudePoint4Full")]
    pub corner_latitude_point4_full: crate::common::DoubleOptionalType,
    #[serde(rename = "CornerLongitudePoint4Full")]
    pub corner_longitude_point4_full: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasAlternatePlatform {
    #[serde(rename = "AlternatePlatformLatitude")]
    pub alternate_platform_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "AlternatePlatformLongitude")]
    pub alternate_platform_longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "AlternatePlatformAltitude")]
    pub alternate_platform_altitude: crate::common::DoubleOptionalType,
    #[serde(rename = "AlternatePlatformName")]
    pub alternate_platform_name: crate::common::StringOptionalType,
    #[serde(rename = "AlternatePlatformHeading")]
    pub alternate_platform_heading: crate::common::DoubleOptionalType,
    #[serde(rename = "AlternatePlatformEllipsoidHeight")]
    pub alternate_platform_ellipsoid_height: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasSensor {
    #[serde(rename = "SensorLatitude")]
    pub sensor_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorLongitude")]
    pub sensor_longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorTrueAltitude")]
    pub sensor_true_altitude: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorHorizontalFieldOfView")]
    pub sensor_horizontal_field_of_view: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorVerticalFieldOfView")]
    pub sensor_vertical_field_of_view: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorRelativeAzimuthAngle")]
    pub sensor_relative_azimuth_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorRelativeElevationAngle")]
    pub sensor_relative_elevation_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorRelativeRollAngle")]
    pub sensor_relative_roll_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorFieldOfViewName")]
    pub sensor_field_of_view_name: crate::common::UShortOptionalType,
    #[serde(rename = "SensorEllipsoidHeight")]
    pub sensor_ellipsoid_height: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorNorthVelocity")]
    pub sensor_north_velocity: crate::common::DoubleOptionalType,
    #[serde(rename = "SensorEastVelocity")]
    pub sensor_east_velocity: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasPlatform {
    #[serde(rename = "PlatformTailNumber")]
    pub platform_tail_number: crate::common::StringOptionalType,
    #[serde(rename = "PlatformHeadingAngle")]
    pub platform_heading_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformPitchAngle")]
    pub platform_pitch_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformRollAngle")]
    pub platform_roll_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformTrueAirspeed")]
    pub platform_true_airspeed: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformIndicatedAirspeed")]
    pub platform_indicated_airspeed: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformDesignation")]
    pub platform_designation: crate::common::StringOptionalType,
    #[serde(rename = "PlatformAngleOfAttack")]
    pub platform_angle_of_attack: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformVerticalSpeed")]
    pub platform_vertical_speed: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformSideslipAngle")]
    pub platform_sideslip_angle: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformGroundSpeed")]
    pub platform_ground_speed: crate::common::UShortOptionalType,
    #[serde(rename = "PlatformFuelRemaining")]
    pub platform_fuel_remaining: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformCallSign")]
    pub platform_call_sign: crate::common::StringOptionalType,
    #[serde(rename = "PlatformMagneticHeading")]
    pub platform_magnetic_heading: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformPitchAngleFull")]
    pub platform_pitch_angle_full: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformRollAngleFull")]
    pub platform_roll_angle_full: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformAngleOfAttackFull")]
    pub platform_angle_of_attack_full: crate::common::DoubleOptionalType,
    #[serde(rename = "PlatformSideSlipAngleFull")]
    pub platform_side_slip_angle_full: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasTarget {
    #[serde(rename = "TargetWidth")]
    pub target_width: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetLocationLatitude")]
    pub target_location_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetLocationLongitude")]
    pub target_location_longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetLocationElevation")]
    pub target_location_elevation: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetTrackGateWidth")]
    pub target_track_gate_width: crate::common::UShortOptionalType,
    #[serde(rename = "TargetTrackGateHeight")]
    pub target_track_gate_height: crate::common::UShortOptionalType,
    #[serde(rename = "TargetErrorEstimateCe90")]
    pub target_error_estimate_ce90: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetErrorEstimateLe90")]
    pub target_error_estimate_le90: crate::common::DoubleOptionalType,
    #[serde(rename = "TargetWidthExtended")]
    pub target_width_extended: crate::common::DoubleOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct UasDatalinkLS {
    #[serde(rename = "Checksum")]
    pub checksum: crate::common::UShortOptionalType,
    #[serde(rename = "PrecisionTimeStamp")]
    pub precision_time_stamp: crate::common::ULongLongOptionalType,
    #[serde(rename = "MissionId")]
    pub mission_id: crate::common::StringOptionalType,
    #[serde(rename = "Platform")]
    pub platform: UasPlatformOptionalType,
    #[serde(rename = "ImageSourceSensor")]
    pub image_source_sensor: crate::common::StringOptionalType,
    #[serde(rename = "ImageCoordinateSystem")]
    pub image_coordinate_system: crate::common::StringOptionalType,
    #[serde(rename = "Sensor")]
    pub sensor: UasSensorOptionalType,
    #[serde(rename = "SlantRange")]
    pub slant_range: crate::common::DoubleOptionalType,
    #[serde(rename = "Target")]
    pub target: UasTargetOptionalType,
    #[serde(rename = "FrameCenterLatitude")]
    pub frame_center_latitude: crate::common::DoubleOptionalType,
    #[serde(rename = "FrameCenterLongitude")]
    pub frame_center_longitude: crate::common::DoubleOptionalType,
    #[serde(rename = "FrameCenterElevation")]
    pub frame_center_elevation: crate::common::DoubleOptionalType,
    #[serde(rename = "OffsetCorner")]
    pub offset_corner: UasOffsetCornerOptionalType,
    #[serde(rename = "IcingDetected")]
    pub icing_detected: crate::common::UShortOptionalType,
    #[serde(rename = "WindDirection")]
    pub wind_direction: crate::common::DoubleOptionalType,
    #[serde(rename = "WindSpeed")]
    pub wind_speed: crate::common::DoubleOptionalType,
    #[serde(rename = "StaticPressure")]
    pub static_pressure: crate::common::DoubleOptionalType,
    #[serde(rename = "DensityAltitude")]
    pub density_altitude: crate::common::DoubleOptionalType,
    #[serde(rename = "OutsideAirTemperature")]
    pub outside_air_temperature: crate::common::LongOptionalType,
    #[serde(rename = "GenericFlagData")]
    pub generic_flag_data: crate::common::UShortOptionalType,
    #[serde(rename = "SecurityLocalSet")]
    pub security_local_set: SecurityMetadataLSOptionalType,
    #[serde(rename = "DifferentialPressure")]
    pub differential_pressure: crate::common::DoubleOptionalType,
    #[serde(rename = "AirfieldBarometricPressure")]
    pub airfield_barometric_pressure: crate::common::DoubleOptionalType,
    #[serde(rename = "AirfieldElevation")]
    pub airfield_elevation: crate::common::DoubleOptionalType,
    #[serde(rename = "RelativeHumidity")]
    pub relative_humidity: crate::common::DoubleOptionalType,
    #[serde(rename = "GroundRange")]
    pub ground_range: crate::common::DoubleOptionalType,
    #[serde(rename = "WeaponLoad")]
    pub weapon_load: crate::common::UShortOptionalType,
    #[serde(rename = "WeaponFired")]
    pub weapon_fired: crate::common::UShortOptionalType,
    #[serde(rename = "LaserPrfCode")]
    pub laser_prf_code: crate::common::UShortOptionalType,
    #[serde(rename = "UasDatalinkLsVersionNumber")]
    pub uas_datalink_ls_version_number: crate::common::UShortOptionalType,
    #[serde(rename = "AlternatePlatform")]
    pub alternate_platform: UasAlternatePlatformOptionalType,
    #[serde(rename = "EventStartTimeUtc")]
    pub event_start_time_utc: crate::common::ULongLongOptionalType,
    #[serde(rename = "RvtLocalSet")]
    pub rvt_local_set: RvtLSListType,
    #[serde(rename = "VmtiLocalSet")]
    pub vmti_local_set: VmtiLSListType,
    #[serde(rename = "OperationalMode")]
    pub operational_mode: crate::common::UShortOptionalType,
    #[serde(rename = "FrameCenterHeightAboveEllipsoid")]
    pub frame_center_height_above_ellipsoid: crate::common::DoubleOptionalType,
    #[serde(rename = "ImageHorizonPixelPack")]
    pub image_horizon_pixel_pack: UasImageHorizonPixelPackOptionalType,
    #[serde(rename = "UasCorner")]
    pub uas_corner: UasCornerOptionalType,
    #[serde(rename = "MiisCoreIdentifier")]
    pub miis_core_identifier: crate::common::StringOptionalType,
    #[serde(rename = "SarMotionImageryLocalSet")]
    pub sar_motion_imagery_local_set: SarMotionImageryMetadataLSOptionalType,
}

