// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type MarkerPositionListType = Vec<MarkerPositionType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VideoObjectSettingsType {
    #[serde(rename = "SupportedVideoChannels")]
    pub supported_video_channels: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MarkerPositionType {
    #[serde(rename = "VideoChannel")]
    pub video_channel: String,
    #[serde(rename = "Position")]
    pub position: crate::common::PositionOptionalType,
    #[serde(rename = "ReferencePosition")]
    pub reference_position: crate::common::PositionOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct MarkerObjectType {
    #[serde(rename = "Height")]
    pub height: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "Width")]
    pub width: crate::common::AngleDegreesOptionalType,
    #[serde(rename = "TypeOfDetectingSensor")]
    pub type_of_detecting_sensor: crate::common::SensorType,
    #[serde(rename = "Identity")]
    pub identity: crate::common::IdentityType,
    #[serde(rename = "DetectingSensorName")]
    pub detecting_sensor_name: String,
    #[serde(rename = "MarkerPositionList")]
    pub marker_position_list: MarkerPositionListType,
    #[serde(rename = "Position")]
    pub position: crate::common::PositionType,
    #[serde(rename = "LinearVelocity")]
    pub linear_velocity: crate::common::LinearVelocityOptionalType,
    #[serde(rename = "Snapshot")]
    pub snapshot: crate::common::ImageOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct KinematicInfoType {
    #[serde(rename = "Position")]
    pub position: crate::common::PositionOptionalType,
    #[serde(rename = "Attitude")]
    pub attitude: crate::common::AttitudeOptionalType,
    #[serde(rename = "LinearVelocity")]
    pub linear_velocity: crate::common::LinearVelocityOptionalType,
}

