// AUTO-GENERATED by idl2rust.py — do not edit by hand.

pub type LotModeOptionalType = Option<lot_mode::Type>;

pub type CameraOrientationListType = Vec<CameraOrientationType>;

pub type VtObjectOptionalType = Option<VtObjectType>;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct CameraOrientationType {
    #[serde(rename = "AxisId")]
    pub axis_id: String,
    #[serde(rename = "Angle")]
    pub angle: crate::common::AngleDegreesType,
    #[serde(rename = "AbsoluteSpeed")]
    pub absolute_speed: crate::common::AngleRateDegreesPerSecType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VtObjectType {
    #[serde(rename = "State")]
    pub state: tracking_state::Type,
    #[serde(rename = "Source")]
    pub source: object_track_source::Type,
    #[serde(rename = "BoundingBox")]
    pub bounding_box: crate::common::PixelRegionType,
    #[serde(rename = "ImageDimensions")]
    pub image_dimensions: crate::common::ImageRegionType,
    #[serde(rename = "EstimatedDistance")]
    pub estimated_distance: crate::common::DistanceMetersOptionalType,
    #[serde(rename = "PixelVelocityX")]
    pub pixel_velocity_x: crate::common::DoubleOptionalType,
    #[serde(rename = "PixelVelocityY")]
    pub pixel_velocity_y: crate::common::DoubleOptionalType,
    #[serde(rename = "VideoChannelSources")]
    pub video_channel_sources: crate::common::StringListType,
    #[serde(rename = "CurrentOrientation")]
    pub current_orientation: CameraOrientationListType,
    #[serde(rename = "ManualGateControl")]
    pub manual_gate_control: crate::common::general_status::Type,
    #[serde(rename = "LosCtrlState")]
    pub los_ctrl_state: vt_los_ctrl_state::Type,
    #[serde(rename = "IsSelected")]
    pub is_selected: bool,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
    #[serde(rename = "FrameNumber")]
    pub frame_number: u64,
    #[serde(rename = "TimeStamp")]
    pub time_stamp: crate::common::TimeType,
    #[serde(rename = "Snapshot")]
    pub snapshot: crate::common::ImageOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct VtProcessingStatType {
    #[serde(rename = "ProcessingTimeSec")]
    pub processing_time_sec: f64,
    #[serde(rename = "FrameDrops")]
    pub frame_drops: u32,
    #[serde(rename = "TimeStamp")]
    pub time_stamp: crate::common::TimeType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LosCtrlStatusType {
    #[serde(rename = "HelpRateInputSourceClientId")]
    pub help_rate_input_source_client_id: String,
    #[serde(rename = "AutoLeadOnState")]
    pub auto_lead_on_state: crate::common::general_status::Type,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct LotStatusType {
    #[serde(rename = "ImageDimensions")]
    pub image_dimensions: crate::common::ImageRegionType,
    #[serde(rename = "LotDefaultInitGate")]
    pub lot_default_init_gate: crate::common::PixelRectSizeOptionalType,
    #[serde(rename = "LotDefaultSearchArea")]
    pub lot_default_search_area: crate::common::PixelRectSizeOptionalType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AtrSettingsType {
    #[serde(rename = "IsConfigAtrMinMaxObjectSizeSupported")]
    pub is_config_atr_min_max_object_size_supported: bool,
    #[serde(rename = "IsCmdAtrTeachInSupported")]
    pub is_cmd_atr_teach_in_supported: bool,
    #[serde(rename = "AdditionalInfo")]
    pub additional_info: crate::common::PropertyListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct AtrStatusType {
    #[serde(rename = "AtrActive")]
    pub atr_active: bool,
    #[serde(rename = "AtrState")]
    pub atr_state: crate::common::general_status::Type,
    #[serde(rename = "ImageDimensions")]
    pub image_dimensions: crate::common::ImageRegionType,
    #[serde(rename = "AtrMinObjectSize")]
    pub atr_min_object_size: crate::common::PixelRectSizeOptionalType,
    #[serde(rename = "AtrMaxObjectSize")]
    pub atr_max_object_size: crate::common::PixelRectSizeOptionalType,
    #[serde(rename = "IsAtrTeachInActive")]
    pub is_atr_teach_in_active: crate::common::BooleanOptionalType,
}

pub mod tracking_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Init")]
        Init,
        #[serde(rename = "Tracking")]
        Tracking,
        #[serde(rename = "Coasting")]
        Coasting,
        #[serde(rename = "Forced_Coasting")]
        Forced_Coasting,
        #[serde(rename = "Deleted")]
        Deleted,
        #[serde(rename = "Lost")]
        Lost,
    }

}

pub mod vt_los_ctrl_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "None")]
        None,
        #[serde(rename = "Init_Leading")]
        Init_Leading,
        #[serde(rename = "Leading")]
        Leading,
    }

}

pub mod object_track_source {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Automatic_Track_Recognition")]
        Automatic_Track_Recognition,
        #[serde(rename = "Lock_On_Track")]
        Lock_On_Track,
        #[serde(rename = "Detection")]
        Detection,
    }

}

pub mod lot_mode {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "Auto")]
        Auto,
        #[serde(rename = "Scene")]
        Scene,
    }

}

pub mod mount_tracking_state {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, schemars::JsonSchema, strum::Display, strum::EnumString)]
    #[allow(non_camel_case_types)] // preserves original IDL variant spelling; see #[serde(rename)]
    pub enum Type {
        #[serde(rename = "No_Tracking")]
        No_Tracking,
        #[serde(rename = "Centering")]
        Centering,
        #[serde(rename = "Centered")]
        Centered,
        #[serde(rename = "Memory_Track_Video_Tracker")]
        Memory_Track_Video_Tracker,
        #[serde(rename = "Memory_Track_Mount")]
        Memory_Track_Mount,
    }

}

