// AUTO-GENERATED by idl2rust.py — do not edit by hand.

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct WatchdogSettingsType {
    #[serde(rename = "WatchableOperations")]
    pub watchable_operations: crate::common::StringListType,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, schemars::JsonSchema, typed_builder::TypedBuilder)]
pub struct WatchStatusType {
    #[serde(rename = "WatchedOperations")]
    pub watched_operations: crate::common::StringListType,
}

